<?php

/**
 * This file is automatically generated. Use 'arc liberate' to rebuild it.
 * @generated
 * @phutil-library-version 2
 */

phutil_register_library_map(array(
  '__library_version__' => 2,
  'class' =>
  array(
    'FacebookFbcodeLintEngine' => 'lint_engine/FacebookFbcodeLintEngine.php',
    'FbcodeCppLinter' => 'cpp_linter/FbcodeCppLinter.php',
    'PfffCppLinter' => 'cpp_linter/PfffCppLinter.php',
    'ArcanistCpplintLinter' => 'cpp_linter/ArcanistCpplintLinter.php',
  ),
  'function' =>
  array(
  ),
  'xmap' =>
  array(
    'FacebookFbcodeLintEngine' => 'ArcanistLintEngine',
    'FbcodeCppLinter' => 'ArcanistLinter',
    'PfffCppLinter' => 'ArcanistLinter',
  ),
));
