// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: agent_service.proto
#ifndef GRPC_agent_5fservice_2eproto__INCLUDED
#define GRPC_agent_5fservice_2eproto__INCLUDED

#include "agent_service.pb.h"

#include <functional>
#include <grpcpp/impl/codegen/async_generic_service.h>
#include <grpcpp/impl/codegen/async_stream.h>
#include <grpcpp/impl/codegen/async_unary_call.h>
#include <grpcpp/impl/codegen/method_handler_impl.h>
#include <grpcpp/impl/codegen/proto_utils.h>
#include <grpcpp/impl/codegen/rpc_method.h>
#include <grpcpp/impl/codegen/service_type.h>
#include <grpcpp/impl/codegen/status.h>
#include <grpcpp/impl/codegen/stub_options.h>
#include <grpcpp/impl/codegen/sync_stream.h>

namespace grpc {
class CompletionQueue;
class Channel;
class ServerCompletionQueue;
class ServerContext;
}  // namespace grpc

namespace agent {

// Agent Service - RocksDB와 Worker 사이의 중개자
class RemoteCompactionAgent final {
 public:
  static constexpr char const* service_full_name() {
    return "agent.RemoteCompactionAgent";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    // Locality 분석 및 최적의 Worker 선택
    virtual ::grpc::Status SelectWorker(::grpc::ClientContext* context, const ::agent::WorkerSelectionRequest& request, ::agent::WorkerSelectionResponse* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::agent::WorkerSelectionResponse>> AsyncSelectWorker(::grpc::ClientContext* context, const ::agent::WorkerSelectionRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::agent::WorkerSelectionResponse>>(AsyncSelectWorkerRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::agent::WorkerSelectionResponse>> PrepareAsyncSelectWorker(::grpc::ClientContext* context, const ::agent::WorkerSelectionRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::agent::WorkerSelectionResponse>>(PrepareAsyncSelectWorkerRaw(context, request, cq));
    }
    // Agent 상태 확인
    virtual ::grpc::Status GetAgentStatus(::grpc::ClientContext* context, const ::agent::AgentStatusRequest& request, ::agent::AgentStatusResponse* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::agent::AgentStatusResponse>> AsyncGetAgentStatus(::grpc::ClientContext* context, const ::agent::AgentStatusRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::agent::AgentStatusResponse>>(AsyncGetAgentStatusRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::agent::AgentStatusResponse>> PrepareAsyncGetAgentStatus(::grpc::ClientContext* context, const ::agent::AgentStatusRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::agent::AgentStatusResponse>>(PrepareAsyncGetAgentStatusRaw(context, request, cq));
    }
    // 컴팩션 작업 제출 (locality 분석 + worker 호출 통합)
    virtual ::grpc::Status SubmitCompaction(::grpc::ClientContext* context, const ::agent::CompactionJobRequest& request, ::agent::CompactionJobResponse* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::agent::CompactionJobResponse>> AsyncSubmitCompaction(::grpc::ClientContext* context, const ::agent::CompactionJobRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::agent::CompactionJobResponse>>(AsyncSubmitCompactionRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::agent::CompactionJobResponse>> PrepareAsyncSubmitCompaction(::grpc::ClientContext* context, const ::agent::CompactionJobRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::agent::CompactionJobResponse>>(PrepareAsyncSubmitCompactionRaw(context, request, cq));
    }
    class experimental_async_interface {
     public:
      virtual ~experimental_async_interface() {}
      // Locality 분석 및 최적의 Worker 선택
      virtual void SelectWorker(::grpc::ClientContext* context, const ::agent::WorkerSelectionRequest* request, ::agent::WorkerSelectionResponse* response, std::function<void(::grpc::Status)>) = 0;
      // Agent 상태 확인
      virtual void GetAgentStatus(::grpc::ClientContext* context, const ::agent::AgentStatusRequest* request, ::agent::AgentStatusResponse* response, std::function<void(::grpc::Status)>) = 0;
      // 컴팩션 작업 제출 (locality 분석 + worker 호출 통합)
      virtual void SubmitCompaction(::grpc::ClientContext* context, const ::agent::CompactionJobRequest* request, ::agent::CompactionJobResponse* response, std::function<void(::grpc::Status)>) = 0;
    };
    virtual class experimental_async_interface* experimental_async() { return nullptr; }
  private:
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::agent::WorkerSelectionResponse>* AsyncSelectWorkerRaw(::grpc::ClientContext* context, const ::agent::WorkerSelectionRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::agent::WorkerSelectionResponse>* PrepareAsyncSelectWorkerRaw(::grpc::ClientContext* context, const ::agent::WorkerSelectionRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::agent::AgentStatusResponse>* AsyncGetAgentStatusRaw(::grpc::ClientContext* context, const ::agent::AgentStatusRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::agent::AgentStatusResponse>* PrepareAsyncGetAgentStatusRaw(::grpc::ClientContext* context, const ::agent::AgentStatusRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::agent::CompactionJobResponse>* AsyncSubmitCompactionRaw(::grpc::ClientContext* context, const ::agent::CompactionJobRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::agent::CompactionJobResponse>* PrepareAsyncSubmitCompactionRaw(::grpc::ClientContext* context, const ::agent::CompactionJobRequest& request, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel);
    ::grpc::Status SelectWorker(::grpc::ClientContext* context, const ::agent::WorkerSelectionRequest& request, ::agent::WorkerSelectionResponse* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::agent::WorkerSelectionResponse>> AsyncSelectWorker(::grpc::ClientContext* context, const ::agent::WorkerSelectionRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::agent::WorkerSelectionResponse>>(AsyncSelectWorkerRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::agent::WorkerSelectionResponse>> PrepareAsyncSelectWorker(::grpc::ClientContext* context, const ::agent::WorkerSelectionRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::agent::WorkerSelectionResponse>>(PrepareAsyncSelectWorkerRaw(context, request, cq));
    }
    ::grpc::Status GetAgentStatus(::grpc::ClientContext* context, const ::agent::AgentStatusRequest& request, ::agent::AgentStatusResponse* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::agent::AgentStatusResponse>> AsyncGetAgentStatus(::grpc::ClientContext* context, const ::agent::AgentStatusRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::agent::AgentStatusResponse>>(AsyncGetAgentStatusRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::agent::AgentStatusResponse>> PrepareAsyncGetAgentStatus(::grpc::ClientContext* context, const ::agent::AgentStatusRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::agent::AgentStatusResponse>>(PrepareAsyncGetAgentStatusRaw(context, request, cq));
    }
    ::grpc::Status SubmitCompaction(::grpc::ClientContext* context, const ::agent::CompactionJobRequest& request, ::agent::CompactionJobResponse* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::agent::CompactionJobResponse>> AsyncSubmitCompaction(::grpc::ClientContext* context, const ::agent::CompactionJobRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::agent::CompactionJobResponse>>(AsyncSubmitCompactionRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::agent::CompactionJobResponse>> PrepareAsyncSubmitCompaction(::grpc::ClientContext* context, const ::agent::CompactionJobRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::agent::CompactionJobResponse>>(PrepareAsyncSubmitCompactionRaw(context, request, cq));
    }
    class experimental_async final :
      public StubInterface::experimental_async_interface {
     public:
      void SelectWorker(::grpc::ClientContext* context, const ::agent::WorkerSelectionRequest* request, ::agent::WorkerSelectionResponse* response, std::function<void(::grpc::Status)>) override;
      void GetAgentStatus(::grpc::ClientContext* context, const ::agent::AgentStatusRequest* request, ::agent::AgentStatusResponse* response, std::function<void(::grpc::Status)>) override;
      void SubmitCompaction(::grpc::ClientContext* context, const ::agent::CompactionJobRequest* request, ::agent::CompactionJobResponse* response, std::function<void(::grpc::Status)>) override;
     private:
      friend class Stub;
      explicit experimental_async(Stub* stub): stub_(stub) { }
      Stub* stub() { return stub_; }
      Stub* stub_;
    };
    class experimental_async_interface* experimental_async() override { return &async_stub_; }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    class experimental_async async_stub_{this};
    ::grpc::ClientAsyncResponseReader< ::agent::WorkerSelectionResponse>* AsyncSelectWorkerRaw(::grpc::ClientContext* context, const ::agent::WorkerSelectionRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::agent::WorkerSelectionResponse>* PrepareAsyncSelectWorkerRaw(::grpc::ClientContext* context, const ::agent::WorkerSelectionRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::agent::AgentStatusResponse>* AsyncGetAgentStatusRaw(::grpc::ClientContext* context, const ::agent::AgentStatusRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::agent::AgentStatusResponse>* PrepareAsyncGetAgentStatusRaw(::grpc::ClientContext* context, const ::agent::AgentStatusRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::agent::CompactionJobResponse>* AsyncSubmitCompactionRaw(::grpc::ClientContext* context, const ::agent::CompactionJobRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::agent::CompactionJobResponse>* PrepareAsyncSubmitCompactionRaw(::grpc::ClientContext* context, const ::agent::CompactionJobRequest& request, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_SelectWorker_;
    const ::grpc::internal::RpcMethod rpcmethod_GetAgentStatus_;
    const ::grpc::internal::RpcMethod rpcmethod_SubmitCompaction_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    // Locality 분석 및 최적의 Worker 선택
    virtual ::grpc::Status SelectWorker(::grpc::ServerContext* context, const ::agent::WorkerSelectionRequest* request, ::agent::WorkerSelectionResponse* response);
    // Agent 상태 확인
    virtual ::grpc::Status GetAgentStatus(::grpc::ServerContext* context, const ::agent::AgentStatusRequest* request, ::agent::AgentStatusResponse* response);
    // 컴팩션 작업 제출 (locality 분석 + worker 호출 통합)
    virtual ::grpc::Status SubmitCompaction(::grpc::ServerContext* context, const ::agent::CompactionJobRequest* request, ::agent::CompactionJobResponse* response);
  };
  template <class BaseClass>
  class WithAsyncMethod_SelectWorker : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithAsyncMethod_SelectWorker() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_SelectWorker() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status SelectWorker(::grpc::ServerContext* context, const ::agent::WorkerSelectionRequest* request, ::agent::WorkerSelectionResponse* response) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestSelectWorker(::grpc::ServerContext* context, ::agent::WorkerSelectionRequest* request, ::grpc::ServerAsyncResponseWriter< ::agent::WorkerSelectionResponse>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_GetAgentStatus : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithAsyncMethod_GetAgentStatus() {
      ::grpc::Service::MarkMethodAsync(1);
    }
    ~WithAsyncMethod_GetAgentStatus() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetAgentStatus(::grpc::ServerContext* context, const ::agent::AgentStatusRequest* request, ::agent::AgentStatusResponse* response) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestGetAgentStatus(::grpc::ServerContext* context, ::agent::AgentStatusRequest* request, ::grpc::ServerAsyncResponseWriter< ::agent::AgentStatusResponse>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(1, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_SubmitCompaction : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithAsyncMethod_SubmitCompaction() {
      ::grpc::Service::MarkMethodAsync(2);
    }
    ~WithAsyncMethod_SubmitCompaction() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status SubmitCompaction(::grpc::ServerContext* context, const ::agent::CompactionJobRequest* request, ::agent::CompactionJobResponse* response) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestSubmitCompaction(::grpc::ServerContext* context, ::agent::CompactionJobRequest* request, ::grpc::ServerAsyncResponseWriter< ::agent::CompactionJobResponse>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(2, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_SelectWorker<WithAsyncMethod_GetAgentStatus<WithAsyncMethod_SubmitCompaction<Service > > > AsyncService;
  template <class BaseClass>
  class WithGenericMethod_SelectWorker : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithGenericMethod_SelectWorker() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_SelectWorker() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status SelectWorker(::grpc::ServerContext* context, const ::agent::WorkerSelectionRequest* request, ::agent::WorkerSelectionResponse* response) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_GetAgentStatus : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithGenericMethod_GetAgentStatus() {
      ::grpc::Service::MarkMethodGeneric(1);
    }
    ~WithGenericMethod_GetAgentStatus() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetAgentStatus(::grpc::ServerContext* context, const ::agent::AgentStatusRequest* request, ::agent::AgentStatusResponse* response) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_SubmitCompaction : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithGenericMethod_SubmitCompaction() {
      ::grpc::Service::MarkMethodGeneric(2);
    }
    ~WithGenericMethod_SubmitCompaction() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status SubmitCompaction(::grpc::ServerContext* context, const ::agent::CompactionJobRequest* request, ::agent::CompactionJobResponse* response) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithRawMethod_SelectWorker : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithRawMethod_SelectWorker() {
      ::grpc::Service::MarkMethodRaw(0);
    }
    ~WithRawMethod_SelectWorker() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status SelectWorker(::grpc::ServerContext* context, const ::agent::WorkerSelectionRequest* request, ::agent::WorkerSelectionResponse* response) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestSelectWorker(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawMethod_GetAgentStatus : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithRawMethod_GetAgentStatus() {
      ::grpc::Service::MarkMethodRaw(1);
    }
    ~WithRawMethod_GetAgentStatus() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetAgentStatus(::grpc::ServerContext* context, const ::agent::AgentStatusRequest* request, ::agent::AgentStatusResponse* response) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestGetAgentStatus(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(1, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawMethod_SubmitCompaction : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithRawMethod_SubmitCompaction() {
      ::grpc::Service::MarkMethodRaw(2);
    }
    ~WithRawMethod_SubmitCompaction() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status SubmitCompaction(::grpc::ServerContext* context, const ::agent::CompactionJobRequest* request, ::agent::CompactionJobResponse* response) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestSubmitCompaction(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(2, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_SelectWorker : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithStreamedUnaryMethod_SelectWorker() {
      ::grpc::Service::MarkMethodStreamed(0,
        new ::grpc::internal::StreamedUnaryHandler< ::agent::WorkerSelectionRequest, ::agent::WorkerSelectionResponse>(std::bind(&WithStreamedUnaryMethod_SelectWorker<BaseClass>::StreamedSelectWorker, this, std::placeholders::_1, std::placeholders::_2)));
    }
    ~WithStreamedUnaryMethod_SelectWorker() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status SelectWorker(::grpc::ServerContext* context, const ::agent::WorkerSelectionRequest* request, ::agent::WorkerSelectionResponse* response) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedSelectWorker(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::agent::WorkerSelectionRequest,::agent::WorkerSelectionResponse>* server_unary_streamer) = 0;
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_GetAgentStatus : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithStreamedUnaryMethod_GetAgentStatus() {
      ::grpc::Service::MarkMethodStreamed(1,
        new ::grpc::internal::StreamedUnaryHandler< ::agent::AgentStatusRequest, ::agent::AgentStatusResponse>(std::bind(&WithStreamedUnaryMethod_GetAgentStatus<BaseClass>::StreamedGetAgentStatus, this, std::placeholders::_1, std::placeholders::_2)));
    }
    ~WithStreamedUnaryMethod_GetAgentStatus() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status GetAgentStatus(::grpc::ServerContext* context, const ::agent::AgentStatusRequest* request, ::agent::AgentStatusResponse* response) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedGetAgentStatus(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::agent::AgentStatusRequest,::agent::AgentStatusResponse>* server_unary_streamer) = 0;
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_SubmitCompaction : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithStreamedUnaryMethod_SubmitCompaction() {
      ::grpc::Service::MarkMethodStreamed(2,
        new ::grpc::internal::StreamedUnaryHandler< ::agent::CompactionJobRequest, ::agent::CompactionJobResponse>(std::bind(&WithStreamedUnaryMethod_SubmitCompaction<BaseClass>::StreamedSubmitCompaction, this, std::placeholders::_1, std::placeholders::_2)));
    }
    ~WithStreamedUnaryMethod_SubmitCompaction() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status SubmitCompaction(::grpc::ServerContext* context, const ::agent::CompactionJobRequest* request, ::agent::CompactionJobResponse* response) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedSubmitCompaction(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::agent::CompactionJobRequest,::agent::CompactionJobResponse>* server_unary_streamer) = 0;
  };
  typedef WithStreamedUnaryMethod_SelectWorker<WithStreamedUnaryMethod_GetAgentStatus<WithStreamedUnaryMethod_SubmitCompaction<Service > > > StreamedUnaryService;
  typedef Service SplitStreamedService;
  typedef WithStreamedUnaryMethod_SelectWorker<WithStreamedUnaryMethod_GetAgentStatus<WithStreamedUnaryMethod_SubmitCompaction<Service > > > StreamedService;
};

}  // namespace agent


#endif  // GRPC_agent_5fservice_2eproto__INCLUDED
