// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: worker_service.proto

#ifndef PROTOBUF_INCLUDED_worker_5fservice_2eproto
#define PROTOBUF_INCLUDED_worker_5fservice_2eproto

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3006001
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3006001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/inlined_string_field.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#define PROTOBUF_INTERNAL_EXPORT_protobuf_worker_5fservice_2eproto 

namespace protobuf_worker_5fservice_2eproto {
// Internal implementation detail -- do not use these members.
struct TableStruct {
  static const ::google::protobuf::internal::ParseTableField entries[];
  static const ::google::protobuf::internal::AuxillaryParseTableField aux[];
  static const ::google::protobuf::internal::ParseTable schema[6];
  static const ::google::protobuf::internal::FieldMetadata field_metadata[];
  static const ::google::protobuf::internal::SerializationTable serialization_table[];
  static const ::google::protobuf::uint32 offsets[];
};
void AddDescriptors();
}  // namespace protobuf_worker_5fservice_2eproto
namespace worker {
class CompactionOptions;
class CompactionOptionsDefaultTypeInternal;
extern CompactionOptionsDefaultTypeInternal _CompactionOptions_default_instance_;
class CompactionRequest;
class CompactionRequestDefaultTypeInternal;
extern CompactionRequestDefaultTypeInternal _CompactionRequest_default_instance_;
class CompactionResponse;
class CompactionResponseDefaultTypeInternal;
extern CompactionResponseDefaultTypeInternal _CompactionResponse_default_instance_;
class OutputFileMetadata;
class OutputFileMetadataDefaultTypeInternal;
extern OutputFileMetadataDefaultTypeInternal _OutputFileMetadata_default_instance_;
class StatusRequest;
class StatusRequestDefaultTypeInternal;
extern StatusRequestDefaultTypeInternal _StatusRequest_default_instance_;
class StatusResponse;
class StatusResponseDefaultTypeInternal;
extern StatusResponseDefaultTypeInternal _StatusResponse_default_instance_;
}  // namespace worker
namespace google {
namespace protobuf {
template<> ::worker::CompactionOptions* Arena::CreateMaybeMessage<::worker::CompactionOptions>(Arena*);
template<> ::worker::CompactionRequest* Arena::CreateMaybeMessage<::worker::CompactionRequest>(Arena*);
template<> ::worker::CompactionResponse* Arena::CreateMaybeMessage<::worker::CompactionResponse>(Arena*);
template<> ::worker::OutputFileMetadata* Arena::CreateMaybeMessage<::worker::OutputFileMetadata>(Arena*);
template<> ::worker::StatusRequest* Arena::CreateMaybeMessage<::worker::StatusRequest>(Arena*);
template<> ::worker::StatusResponse* Arena::CreateMaybeMessage<::worker::StatusResponse>(Arena*);
}  // namespace protobuf
}  // namespace google
namespace worker {

// ===================================================================

class CompactionRequest : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:worker.CompactionRequest) */ {
 public:
  CompactionRequest();
  virtual ~CompactionRequest();

  CompactionRequest(const CompactionRequest& from);

  inline CompactionRequest& operator=(const CompactionRequest& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  CompactionRequest(CompactionRequest&& from) noexcept
    : CompactionRequest() {
    *this = ::std::move(from);
  }

  inline CompactionRequest& operator=(CompactionRequest&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const CompactionRequest& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const CompactionRequest* internal_default_instance() {
    return reinterpret_cast<const CompactionRequest*>(
               &_CompactionRequest_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  void Swap(CompactionRequest* other);
  friend void swap(CompactionRequest& a, CompactionRequest& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline CompactionRequest* New() const final {
    return CreateMaybeMessage<CompactionRequest>(NULL);
  }

  CompactionRequest* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<CompactionRequest>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const CompactionRequest& from);
  void MergeFrom(const CompactionRequest& from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(CompactionRequest* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated string input_sst_files = 2;
  int input_sst_files_size() const;
  void clear_input_sst_files();
  static const int kInputSstFilesFieldNumber = 2;
  const ::std::string& input_sst_files(int index) const;
  ::std::string* mutable_input_sst_files(int index);
  void set_input_sst_files(int index, const ::std::string& value);
  #if LANG_CXX11
  void set_input_sst_files(int index, ::std::string&& value);
  #endif
  void set_input_sst_files(int index, const char* value);
  void set_input_sst_files(int index, const char* value, size_t size);
  ::std::string* add_input_sst_files();
  void add_input_sst_files(const ::std::string& value);
  #if LANG_CXX11
  void add_input_sst_files(::std::string&& value);
  #endif
  void add_input_sst_files(const char* value);
  void add_input_sst_files(const char* value, size_t size);
  const ::google::protobuf::RepeatedPtrField< ::std::string>& input_sst_files() const;
  ::google::protobuf::RepeatedPtrField< ::std::string>* mutable_input_sst_files();

  // string job_id = 1;
  void clear_job_id();
  static const int kJobIdFieldNumber = 1;
  const ::std::string& job_id() const;
  void set_job_id(const ::std::string& value);
  #if LANG_CXX11
  void set_job_id(::std::string&& value);
  #endif
  void set_job_id(const char* value);
  void set_job_id(const char* value, size_t size);
  ::std::string* mutable_job_id();
  ::std::string* release_job_id();
  void set_allocated_job_id(::std::string* job_id);

  // .worker.CompactionOptions options = 3;
  bool has_options() const;
  void clear_options();
  static const int kOptionsFieldNumber = 3;
  private:
  const ::worker::CompactionOptions& _internal_options() const;
  public:
  const ::worker::CompactionOptions& options() const;
  ::worker::CompactionOptions* release_options();
  ::worker::CompactionOptions* mutable_options();
  void set_allocated_options(::worker::CompactionOptions* options);

  // @@protoc_insertion_point(class_scope:worker.CompactionRequest)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::RepeatedPtrField< ::std::string> input_sst_files_;
  ::google::protobuf::internal::ArenaStringPtr job_id_;
  ::worker::CompactionOptions* options_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  friend struct ::protobuf_worker_5fservice_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class CompactionOptions : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:worker.CompactionOptions) */ {
 public:
  CompactionOptions();
  virtual ~CompactionOptions();

  CompactionOptions(const CompactionOptions& from);

  inline CompactionOptions& operator=(const CompactionOptions& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  CompactionOptions(CompactionOptions&& from) noexcept
    : CompactionOptions() {
    *this = ::std::move(from);
  }

  inline CompactionOptions& operator=(CompactionOptions&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const CompactionOptions& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const CompactionOptions* internal_default_instance() {
    return reinterpret_cast<const CompactionOptions*>(
               &_CompactionOptions_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  void Swap(CompactionOptions* other);
  friend void swap(CompactionOptions& a, CompactionOptions& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline CompactionOptions* New() const final {
    return CreateMaybeMessage<CompactionOptions>(NULL);
  }

  CompactionOptions* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<CompactionOptions>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const CompactionOptions& from);
  void MergeFrom(const CompactionOptions& from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(CompactionOptions* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // string compression_type = 1;
  void clear_compression_type();
  static const int kCompressionTypeFieldNumber = 1;
  const ::std::string& compression_type() const;
  void set_compression_type(const ::std::string& value);
  #if LANG_CXX11
  void set_compression_type(::std::string&& value);
  #endif
  void set_compression_type(const char* value);
  void set_compression_type(const char* value, size_t size);
  ::std::string* mutable_compression_type();
  ::std::string* release_compression_type();
  void set_allocated_compression_type(::std::string* compression_type);

  // uint64 target_file_size = 2;
  void clear_target_file_size();
  static const int kTargetFileSizeFieldNumber = 2;
  ::google::protobuf::uint64 target_file_size() const;
  void set_target_file_size(::google::protobuf::uint64 value);

  // bool enable_statistics = 3;
  void clear_enable_statistics();
  static const int kEnableStatisticsFieldNumber = 3;
  bool enable_statistics() const;
  void set_enable_statistics(bool value);

  // @@protoc_insertion_point(class_scope:worker.CompactionOptions)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::ArenaStringPtr compression_type_;
  ::google::protobuf::uint64 target_file_size_;
  bool enable_statistics_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  friend struct ::protobuf_worker_5fservice_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class OutputFileMetadata : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:worker.OutputFileMetadata) */ {
 public:
  OutputFileMetadata();
  virtual ~OutputFileMetadata();

  OutputFileMetadata(const OutputFileMetadata& from);

  inline OutputFileMetadata& operator=(const OutputFileMetadata& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  OutputFileMetadata(OutputFileMetadata&& from) noexcept
    : OutputFileMetadata() {
    *this = ::std::move(from);
  }

  inline OutputFileMetadata& operator=(OutputFileMetadata&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const OutputFileMetadata& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const OutputFileMetadata* internal_default_instance() {
    return reinterpret_cast<const OutputFileMetadata*>(
               &_OutputFileMetadata_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    2;

  void Swap(OutputFileMetadata* other);
  friend void swap(OutputFileMetadata& a, OutputFileMetadata& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline OutputFileMetadata* New() const final {
    return CreateMaybeMessage<OutputFileMetadata>(NULL);
  }

  OutputFileMetadata* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<OutputFileMetadata>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const OutputFileMetadata& from);
  void MergeFrom(const OutputFileMetadata& from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(OutputFileMetadata* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // string file_path = 1;
  void clear_file_path();
  static const int kFilePathFieldNumber = 1;
  const ::std::string& file_path() const;
  void set_file_path(const ::std::string& value);
  #if LANG_CXX11
  void set_file_path(::std::string&& value);
  #endif
  void set_file_path(const char* value);
  void set_file_path(const char* value, size_t size);
  ::std::string* mutable_file_path();
  ::std::string* release_file_path();
  void set_allocated_file_path(::std::string* file_path);

  // string smallest_key_hex = 2;
  void clear_smallest_key_hex();
  static const int kSmallestKeyHexFieldNumber = 2;
  const ::std::string& smallest_key_hex() const;
  void set_smallest_key_hex(const ::std::string& value);
  #if LANG_CXX11
  void set_smallest_key_hex(::std::string&& value);
  #endif
  void set_smallest_key_hex(const char* value);
  void set_smallest_key_hex(const char* value, size_t size);
  ::std::string* mutable_smallest_key_hex();
  ::std::string* release_smallest_key_hex();
  void set_allocated_smallest_key_hex(::std::string* smallest_key_hex);

  // string largest_key_hex = 3;
  void clear_largest_key_hex();
  static const int kLargestKeyHexFieldNumber = 3;
  const ::std::string& largest_key_hex() const;
  void set_largest_key_hex(const ::std::string& value);
  #if LANG_CXX11
  void set_largest_key_hex(::std::string&& value);
  #endif
  void set_largest_key_hex(const char* value);
  void set_largest_key_hex(const char* value, size_t size);
  ::std::string* mutable_largest_key_hex();
  ::std::string* release_largest_key_hex();
  void set_allocated_largest_key_hex(::std::string* largest_key_hex);

  // uint64 num_entries = 4;
  void clear_num_entries();
  static const int kNumEntriesFieldNumber = 4;
  ::google::protobuf::uint64 num_entries() const;
  void set_num_entries(::google::protobuf::uint64 value);

  // uint64 file_size = 5;
  void clear_file_size();
  static const int kFileSizeFieldNumber = 5;
  ::google::protobuf::uint64 file_size() const;
  void set_file_size(::google::protobuf::uint64 value);

  // @@protoc_insertion_point(class_scope:worker.OutputFileMetadata)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::ArenaStringPtr file_path_;
  ::google::protobuf::internal::ArenaStringPtr smallest_key_hex_;
  ::google::protobuf::internal::ArenaStringPtr largest_key_hex_;
  ::google::protobuf::uint64 num_entries_;
  ::google::protobuf::uint64 file_size_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  friend struct ::protobuf_worker_5fservice_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class CompactionResponse : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:worker.CompactionResponse) */ {
 public:
  CompactionResponse();
  virtual ~CompactionResponse();

  CompactionResponse(const CompactionResponse& from);

  inline CompactionResponse& operator=(const CompactionResponse& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  CompactionResponse(CompactionResponse&& from) noexcept
    : CompactionResponse() {
    *this = ::std::move(from);
  }

  inline CompactionResponse& operator=(CompactionResponse&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const CompactionResponse& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const CompactionResponse* internal_default_instance() {
    return reinterpret_cast<const CompactionResponse*>(
               &_CompactionResponse_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    3;

  void Swap(CompactionResponse* other);
  friend void swap(CompactionResponse& a, CompactionResponse& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline CompactionResponse* New() const final {
    return CreateMaybeMessage<CompactionResponse>(NULL);
  }

  CompactionResponse* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<CompactionResponse>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const CompactionResponse& from);
  void MergeFrom(const CompactionResponse& from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(CompactionResponse* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated string output_sst_files = 3;
  int output_sst_files_size() const;
  void clear_output_sst_files();
  static const int kOutputSstFilesFieldNumber = 3;
  const ::std::string& output_sst_files(int index) const;
  ::std::string* mutable_output_sst_files(int index);
  void set_output_sst_files(int index, const ::std::string& value);
  #if LANG_CXX11
  void set_output_sst_files(int index, ::std::string&& value);
  #endif
  void set_output_sst_files(int index, const char* value);
  void set_output_sst_files(int index, const char* value, size_t size);
  ::std::string* add_output_sst_files();
  void add_output_sst_files(const ::std::string& value);
  #if LANG_CXX11
  void add_output_sst_files(::std::string&& value);
  #endif
  void add_output_sst_files(const char* value);
  void add_output_sst_files(const char* value, size_t size);
  const ::google::protobuf::RepeatedPtrField< ::std::string>& output_sst_files() const;
  ::google::protobuf::RepeatedPtrField< ::std::string>* mutable_output_sst_files();

  // repeated .worker.OutputFileMetadata output_file_metadata = 14;
  int output_file_metadata_size() const;
  void clear_output_file_metadata();
  static const int kOutputFileMetadataFieldNumber = 14;
  ::worker::OutputFileMetadata* mutable_output_file_metadata(int index);
  ::google::protobuf::RepeatedPtrField< ::worker::OutputFileMetadata >*
      mutable_output_file_metadata();
  const ::worker::OutputFileMetadata& output_file_metadata(int index) const;
  ::worker::OutputFileMetadata* add_output_file_metadata();
  const ::google::protobuf::RepeatedPtrField< ::worker::OutputFileMetadata >&
      output_file_metadata() const;

  // string job_id = 2;
  void clear_job_id();
  static const int kJobIdFieldNumber = 2;
  const ::std::string& job_id() const;
  void set_job_id(const ::std::string& value);
  #if LANG_CXX11
  void set_job_id(::std::string&& value);
  #endif
  void set_job_id(const char* value);
  void set_job_id(const char* value, size_t size);
  ::std::string* mutable_job_id();
  ::std::string* release_job_id();
  void set_allocated_job_id(::std::string* job_id);

  // string error_message = 8;
  void clear_error_message();
  static const int kErrorMessageFieldNumber = 8;
  const ::std::string& error_message() const;
  void set_error_message(const ::std::string& value);
  #if LANG_CXX11
  void set_error_message(::std::string&& value);
  #endif
  void set_error_message(const char* value);
  void set_error_message(const char* value, size_t size);
  ::std::string* mutable_error_message();
  ::std::string* release_error_message();
  void set_allocated_error_message(::std::string* error_message);

  // string smallest_key = 9;
  void clear_smallest_key();
  static const int kSmallestKeyFieldNumber = 9;
  const ::std::string& smallest_key() const;
  void set_smallest_key(const ::std::string& value);
  #if LANG_CXX11
  void set_smallest_key(::std::string&& value);
  #endif
  void set_smallest_key(const char* value);
  void set_smallest_key(const char* value, size_t size);
  ::std::string* mutable_smallest_key();
  ::std::string* release_smallest_key();
  void set_allocated_smallest_key(::std::string* smallest_key);

  // string largest_key = 10;
  void clear_largest_key();
  static const int kLargestKeyFieldNumber = 10;
  const ::std::string& largest_key() const;
  void set_largest_key(const ::std::string& value);
  #if LANG_CXX11
  void set_largest_key(::std::string&& value);
  #endif
  void set_largest_key(const char* value);
  void set_largest_key(const char* value, size_t size);
  ::std::string* mutable_largest_key();
  ::std::string* release_largest_key();
  void set_allocated_largest_key(::std::string* largest_key);

  // uint64 input_size_bytes = 4;
  void clear_input_size_bytes();
  static const int kInputSizeBytesFieldNumber = 4;
  ::google::protobuf::uint64 input_size_bytes() const;
  void set_input_size_bytes(::google::protobuf::uint64 value);

  // uint64 output_size_bytes = 5;
  void clear_output_size_bytes();
  static const int kOutputSizeBytesFieldNumber = 5;
  ::google::protobuf::uint64 output_size_bytes() const;
  void set_output_size_bytes(::google::protobuf::uint64 value);

  // double compression_ratio = 6;
  void clear_compression_ratio();
  static const int kCompressionRatioFieldNumber = 6;
  double compression_ratio() const;
  void set_compression_ratio(double value);

  // uint64 processing_time_ms = 7;
  void clear_processing_time_ms();
  static const int kProcessingTimeMsFieldNumber = 7;
  ::google::protobuf::uint64 processing_time_ms() const;
  void set_processing_time_ms(::google::protobuf::uint64 value);

  // uint64 num_entries = 11;
  void clear_num_entries();
  static const int kNumEntriesFieldNumber = 11;
  ::google::protobuf::uint64 num_entries() const;
  void set_num_entries(::google::protobuf::uint64 value);

  // uint64 file_size = 12;
  void clear_file_size();
  static const int kFileSizeFieldNumber = 12;
  ::google::protobuf::uint64 file_size() const;
  void set_file_size(::google::protobuf::uint64 value);

  // uint64 num_input_entries = 13;
  void clear_num_input_entries();
  static const int kNumInputEntriesFieldNumber = 13;
  ::google::protobuf::uint64 num_input_entries() const;
  void set_num_input_entries(::google::protobuf::uint64 value);

  // bool success = 1;
  void clear_success();
  static const int kSuccessFieldNumber = 1;
  bool success() const;
  void set_success(bool value);

  // @@protoc_insertion_point(class_scope:worker.CompactionResponse)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::RepeatedPtrField< ::std::string> output_sst_files_;
  ::google::protobuf::RepeatedPtrField< ::worker::OutputFileMetadata > output_file_metadata_;
  ::google::protobuf::internal::ArenaStringPtr job_id_;
  ::google::protobuf::internal::ArenaStringPtr error_message_;
  ::google::protobuf::internal::ArenaStringPtr smallest_key_;
  ::google::protobuf::internal::ArenaStringPtr largest_key_;
  ::google::protobuf::uint64 input_size_bytes_;
  ::google::protobuf::uint64 output_size_bytes_;
  double compression_ratio_;
  ::google::protobuf::uint64 processing_time_ms_;
  ::google::protobuf::uint64 num_entries_;
  ::google::protobuf::uint64 file_size_;
  ::google::protobuf::uint64 num_input_entries_;
  bool success_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  friend struct ::protobuf_worker_5fservice_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class StatusRequest : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:worker.StatusRequest) */ {
 public:
  StatusRequest();
  virtual ~StatusRequest();

  StatusRequest(const StatusRequest& from);

  inline StatusRequest& operator=(const StatusRequest& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  StatusRequest(StatusRequest&& from) noexcept
    : StatusRequest() {
    *this = ::std::move(from);
  }

  inline StatusRequest& operator=(StatusRequest&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const StatusRequest& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const StatusRequest* internal_default_instance() {
    return reinterpret_cast<const StatusRequest*>(
               &_StatusRequest_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    4;

  void Swap(StatusRequest* other);
  friend void swap(StatusRequest& a, StatusRequest& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline StatusRequest* New() const final {
    return CreateMaybeMessage<StatusRequest>(NULL);
  }

  StatusRequest* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<StatusRequest>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const StatusRequest& from);
  void MergeFrom(const StatusRequest& from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(StatusRequest* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // @@protoc_insertion_point(class_scope:worker.StatusRequest)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  friend struct ::protobuf_worker_5fservice_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class StatusResponse : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:worker.StatusResponse) */ {
 public:
  StatusResponse();
  virtual ~StatusResponse();

  StatusResponse(const StatusResponse& from);

  inline StatusResponse& operator=(const StatusResponse& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  StatusResponse(StatusResponse&& from) noexcept
    : StatusResponse() {
    *this = ::std::move(from);
  }

  inline StatusResponse& operator=(StatusResponse&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const StatusResponse& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const StatusResponse* internal_default_instance() {
    return reinterpret_cast<const StatusResponse*>(
               &_StatusResponse_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    5;

  void Swap(StatusResponse* other);
  friend void swap(StatusResponse& a, StatusResponse& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline StatusResponse* New() const final {
    return CreateMaybeMessage<StatusResponse>(NULL);
  }

  StatusResponse* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<StatusResponse>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const StatusResponse& from);
  void MergeFrom(const StatusResponse& from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(StatusResponse* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // string node_name = 1;
  void clear_node_name();
  static const int kNodeNameFieldNumber = 1;
  const ::std::string& node_name() const;
  void set_node_name(const ::std::string& value);
  #if LANG_CXX11
  void set_node_name(::std::string&& value);
  #endif
  void set_node_name(const char* value);
  void set_node_name(const char* value, size_t size);
  ::std::string* mutable_node_name();
  ::std::string* release_node_name();
  void set_allocated_node_name(::std::string* node_name);

  // bool is_healthy = 2;
  void clear_is_healthy();
  static const int kIsHealthyFieldNumber = 2;
  bool is_healthy() const;
  void set_is_healthy(bool value);

  // int32 active_jobs = 3;
  void clear_active_jobs();
  static const int kActiveJobsFieldNumber = 3;
  ::google::protobuf::int32 active_jobs() const;
  void set_active_jobs(::google::protobuf::int32 value);

  // int64 avg_processing_time_ms = 5;
  void clear_avg_processing_time_ms();
  static const int kAvgProcessingTimeMsFieldNumber = 5;
  ::google::protobuf::int64 avg_processing_time_ms() const;
  void set_avg_processing_time_ms(::google::protobuf::int64 value);

  // int32 total_completed = 4;
  void clear_total_completed();
  static const int kTotalCompletedFieldNumber = 4;
  ::google::protobuf::int32 total_completed() const;
  void set_total_completed(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:worker.StatusResponse)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::ArenaStringPtr node_name_;
  bool is_healthy_;
  ::google::protobuf::int32 active_jobs_;
  ::google::protobuf::int64 avg_processing_time_ms_;
  ::google::protobuf::int32 total_completed_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  friend struct ::protobuf_worker_5fservice_2eproto::TableStruct;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// CompactionRequest

// string job_id = 1;
inline void CompactionRequest::clear_job_id() {
  job_id_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& CompactionRequest::job_id() const {
  // @@protoc_insertion_point(field_get:worker.CompactionRequest.job_id)
  return job_id_.GetNoArena();
}
inline void CompactionRequest::set_job_id(const ::std::string& value) {
  
  job_id_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:worker.CompactionRequest.job_id)
}
#if LANG_CXX11
inline void CompactionRequest::set_job_id(::std::string&& value) {
  
  job_id_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:worker.CompactionRequest.job_id)
}
#endif
inline void CompactionRequest::set_job_id(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  job_id_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:worker.CompactionRequest.job_id)
}
inline void CompactionRequest::set_job_id(const char* value, size_t size) {
  
  job_id_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:worker.CompactionRequest.job_id)
}
inline ::std::string* CompactionRequest::mutable_job_id() {
  
  // @@protoc_insertion_point(field_mutable:worker.CompactionRequest.job_id)
  return job_id_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* CompactionRequest::release_job_id() {
  // @@protoc_insertion_point(field_release:worker.CompactionRequest.job_id)
  
  return job_id_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void CompactionRequest::set_allocated_job_id(::std::string* job_id) {
  if (job_id != NULL) {
    
  } else {
    
  }
  job_id_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), job_id);
  // @@protoc_insertion_point(field_set_allocated:worker.CompactionRequest.job_id)
}

// repeated string input_sst_files = 2;
inline int CompactionRequest::input_sst_files_size() const {
  return input_sst_files_.size();
}
inline void CompactionRequest::clear_input_sst_files() {
  input_sst_files_.Clear();
}
inline const ::std::string& CompactionRequest::input_sst_files(int index) const {
  // @@protoc_insertion_point(field_get:worker.CompactionRequest.input_sst_files)
  return input_sst_files_.Get(index);
}
inline ::std::string* CompactionRequest::mutable_input_sst_files(int index) {
  // @@protoc_insertion_point(field_mutable:worker.CompactionRequest.input_sst_files)
  return input_sst_files_.Mutable(index);
}
inline void CompactionRequest::set_input_sst_files(int index, const ::std::string& value) {
  // @@protoc_insertion_point(field_set:worker.CompactionRequest.input_sst_files)
  input_sst_files_.Mutable(index)->assign(value);
}
#if LANG_CXX11
inline void CompactionRequest::set_input_sst_files(int index, ::std::string&& value) {
  // @@protoc_insertion_point(field_set:worker.CompactionRequest.input_sst_files)
  input_sst_files_.Mutable(index)->assign(std::move(value));
}
#endif
inline void CompactionRequest::set_input_sst_files(int index, const char* value) {
  GOOGLE_DCHECK(value != NULL);
  input_sst_files_.Mutable(index)->assign(value);
  // @@protoc_insertion_point(field_set_char:worker.CompactionRequest.input_sst_files)
}
inline void CompactionRequest::set_input_sst_files(int index, const char* value, size_t size) {
  input_sst_files_.Mutable(index)->assign(
    reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_set_pointer:worker.CompactionRequest.input_sst_files)
}
inline ::std::string* CompactionRequest::add_input_sst_files() {
  // @@protoc_insertion_point(field_add_mutable:worker.CompactionRequest.input_sst_files)
  return input_sst_files_.Add();
}
inline void CompactionRequest::add_input_sst_files(const ::std::string& value) {
  input_sst_files_.Add()->assign(value);
  // @@protoc_insertion_point(field_add:worker.CompactionRequest.input_sst_files)
}
#if LANG_CXX11
inline void CompactionRequest::add_input_sst_files(::std::string&& value) {
  input_sst_files_.Add(std::move(value));
  // @@protoc_insertion_point(field_add:worker.CompactionRequest.input_sst_files)
}
#endif
inline void CompactionRequest::add_input_sst_files(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  input_sst_files_.Add()->assign(value);
  // @@protoc_insertion_point(field_add_char:worker.CompactionRequest.input_sst_files)
}
inline void CompactionRequest::add_input_sst_files(const char* value, size_t size) {
  input_sst_files_.Add()->assign(reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_add_pointer:worker.CompactionRequest.input_sst_files)
}
inline const ::google::protobuf::RepeatedPtrField< ::std::string>&
CompactionRequest::input_sst_files() const {
  // @@protoc_insertion_point(field_list:worker.CompactionRequest.input_sst_files)
  return input_sst_files_;
}
inline ::google::protobuf::RepeatedPtrField< ::std::string>*
CompactionRequest::mutable_input_sst_files() {
  // @@protoc_insertion_point(field_mutable_list:worker.CompactionRequest.input_sst_files)
  return &input_sst_files_;
}

// .worker.CompactionOptions options = 3;
inline bool CompactionRequest::has_options() const {
  return this != internal_default_instance() && options_ != NULL;
}
inline void CompactionRequest::clear_options() {
  if (GetArenaNoVirtual() == NULL && options_ != NULL) {
    delete options_;
  }
  options_ = NULL;
}
inline const ::worker::CompactionOptions& CompactionRequest::_internal_options() const {
  return *options_;
}
inline const ::worker::CompactionOptions& CompactionRequest::options() const {
  const ::worker::CompactionOptions* p = options_;
  // @@protoc_insertion_point(field_get:worker.CompactionRequest.options)
  return p != NULL ? *p : *reinterpret_cast<const ::worker::CompactionOptions*>(
      &::worker::_CompactionOptions_default_instance_);
}
inline ::worker::CompactionOptions* CompactionRequest::release_options() {
  // @@protoc_insertion_point(field_release:worker.CompactionRequest.options)
  
  ::worker::CompactionOptions* temp = options_;
  options_ = NULL;
  return temp;
}
inline ::worker::CompactionOptions* CompactionRequest::mutable_options() {
  
  if (options_ == NULL) {
    auto* p = CreateMaybeMessage<::worker::CompactionOptions>(GetArenaNoVirtual());
    options_ = p;
  }
  // @@protoc_insertion_point(field_mutable:worker.CompactionRequest.options)
  return options_;
}
inline void CompactionRequest::set_allocated_options(::worker::CompactionOptions* options) {
  ::google::protobuf::Arena* message_arena = GetArenaNoVirtual();
  if (message_arena == NULL) {
    delete options_;
  }
  if (options) {
    ::google::protobuf::Arena* submessage_arena = NULL;
    if (message_arena != submessage_arena) {
      options = ::google::protobuf::internal::GetOwnedMessage(
          message_arena, options, submessage_arena);
    }
    
  } else {
    
  }
  options_ = options;
  // @@protoc_insertion_point(field_set_allocated:worker.CompactionRequest.options)
}

// -------------------------------------------------------------------

// CompactionOptions

// string compression_type = 1;
inline void CompactionOptions::clear_compression_type() {
  compression_type_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& CompactionOptions::compression_type() const {
  // @@protoc_insertion_point(field_get:worker.CompactionOptions.compression_type)
  return compression_type_.GetNoArena();
}
inline void CompactionOptions::set_compression_type(const ::std::string& value) {
  
  compression_type_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:worker.CompactionOptions.compression_type)
}
#if LANG_CXX11
inline void CompactionOptions::set_compression_type(::std::string&& value) {
  
  compression_type_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:worker.CompactionOptions.compression_type)
}
#endif
inline void CompactionOptions::set_compression_type(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  compression_type_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:worker.CompactionOptions.compression_type)
}
inline void CompactionOptions::set_compression_type(const char* value, size_t size) {
  
  compression_type_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:worker.CompactionOptions.compression_type)
}
inline ::std::string* CompactionOptions::mutable_compression_type() {
  
  // @@protoc_insertion_point(field_mutable:worker.CompactionOptions.compression_type)
  return compression_type_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* CompactionOptions::release_compression_type() {
  // @@protoc_insertion_point(field_release:worker.CompactionOptions.compression_type)
  
  return compression_type_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void CompactionOptions::set_allocated_compression_type(::std::string* compression_type) {
  if (compression_type != NULL) {
    
  } else {
    
  }
  compression_type_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), compression_type);
  // @@protoc_insertion_point(field_set_allocated:worker.CompactionOptions.compression_type)
}

// uint64 target_file_size = 2;
inline void CompactionOptions::clear_target_file_size() {
  target_file_size_ = GOOGLE_ULONGLONG(0);
}
inline ::google::protobuf::uint64 CompactionOptions::target_file_size() const {
  // @@protoc_insertion_point(field_get:worker.CompactionOptions.target_file_size)
  return target_file_size_;
}
inline void CompactionOptions::set_target_file_size(::google::protobuf::uint64 value) {
  
  target_file_size_ = value;
  // @@protoc_insertion_point(field_set:worker.CompactionOptions.target_file_size)
}

// bool enable_statistics = 3;
inline void CompactionOptions::clear_enable_statistics() {
  enable_statistics_ = false;
}
inline bool CompactionOptions::enable_statistics() const {
  // @@protoc_insertion_point(field_get:worker.CompactionOptions.enable_statistics)
  return enable_statistics_;
}
inline void CompactionOptions::set_enable_statistics(bool value) {
  
  enable_statistics_ = value;
  // @@protoc_insertion_point(field_set:worker.CompactionOptions.enable_statistics)
}

// -------------------------------------------------------------------

// OutputFileMetadata

// string file_path = 1;
inline void OutputFileMetadata::clear_file_path() {
  file_path_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& OutputFileMetadata::file_path() const {
  // @@protoc_insertion_point(field_get:worker.OutputFileMetadata.file_path)
  return file_path_.GetNoArena();
}
inline void OutputFileMetadata::set_file_path(const ::std::string& value) {
  
  file_path_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:worker.OutputFileMetadata.file_path)
}
#if LANG_CXX11
inline void OutputFileMetadata::set_file_path(::std::string&& value) {
  
  file_path_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:worker.OutputFileMetadata.file_path)
}
#endif
inline void OutputFileMetadata::set_file_path(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  file_path_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:worker.OutputFileMetadata.file_path)
}
inline void OutputFileMetadata::set_file_path(const char* value, size_t size) {
  
  file_path_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:worker.OutputFileMetadata.file_path)
}
inline ::std::string* OutputFileMetadata::mutable_file_path() {
  
  // @@protoc_insertion_point(field_mutable:worker.OutputFileMetadata.file_path)
  return file_path_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* OutputFileMetadata::release_file_path() {
  // @@protoc_insertion_point(field_release:worker.OutputFileMetadata.file_path)
  
  return file_path_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void OutputFileMetadata::set_allocated_file_path(::std::string* file_path) {
  if (file_path != NULL) {
    
  } else {
    
  }
  file_path_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), file_path);
  // @@protoc_insertion_point(field_set_allocated:worker.OutputFileMetadata.file_path)
}

// string smallest_key_hex = 2;
inline void OutputFileMetadata::clear_smallest_key_hex() {
  smallest_key_hex_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& OutputFileMetadata::smallest_key_hex() const {
  // @@protoc_insertion_point(field_get:worker.OutputFileMetadata.smallest_key_hex)
  return smallest_key_hex_.GetNoArena();
}
inline void OutputFileMetadata::set_smallest_key_hex(const ::std::string& value) {
  
  smallest_key_hex_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:worker.OutputFileMetadata.smallest_key_hex)
}
#if LANG_CXX11
inline void OutputFileMetadata::set_smallest_key_hex(::std::string&& value) {
  
  smallest_key_hex_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:worker.OutputFileMetadata.smallest_key_hex)
}
#endif
inline void OutputFileMetadata::set_smallest_key_hex(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  smallest_key_hex_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:worker.OutputFileMetadata.smallest_key_hex)
}
inline void OutputFileMetadata::set_smallest_key_hex(const char* value, size_t size) {
  
  smallest_key_hex_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:worker.OutputFileMetadata.smallest_key_hex)
}
inline ::std::string* OutputFileMetadata::mutable_smallest_key_hex() {
  
  // @@protoc_insertion_point(field_mutable:worker.OutputFileMetadata.smallest_key_hex)
  return smallest_key_hex_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* OutputFileMetadata::release_smallest_key_hex() {
  // @@protoc_insertion_point(field_release:worker.OutputFileMetadata.smallest_key_hex)
  
  return smallest_key_hex_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void OutputFileMetadata::set_allocated_smallest_key_hex(::std::string* smallest_key_hex) {
  if (smallest_key_hex != NULL) {
    
  } else {
    
  }
  smallest_key_hex_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), smallest_key_hex);
  // @@protoc_insertion_point(field_set_allocated:worker.OutputFileMetadata.smallest_key_hex)
}

// string largest_key_hex = 3;
inline void OutputFileMetadata::clear_largest_key_hex() {
  largest_key_hex_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& OutputFileMetadata::largest_key_hex() const {
  // @@protoc_insertion_point(field_get:worker.OutputFileMetadata.largest_key_hex)
  return largest_key_hex_.GetNoArena();
}
inline void OutputFileMetadata::set_largest_key_hex(const ::std::string& value) {
  
  largest_key_hex_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:worker.OutputFileMetadata.largest_key_hex)
}
#if LANG_CXX11
inline void OutputFileMetadata::set_largest_key_hex(::std::string&& value) {
  
  largest_key_hex_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:worker.OutputFileMetadata.largest_key_hex)
}
#endif
inline void OutputFileMetadata::set_largest_key_hex(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  largest_key_hex_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:worker.OutputFileMetadata.largest_key_hex)
}
inline void OutputFileMetadata::set_largest_key_hex(const char* value, size_t size) {
  
  largest_key_hex_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:worker.OutputFileMetadata.largest_key_hex)
}
inline ::std::string* OutputFileMetadata::mutable_largest_key_hex() {
  
  // @@protoc_insertion_point(field_mutable:worker.OutputFileMetadata.largest_key_hex)
  return largest_key_hex_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* OutputFileMetadata::release_largest_key_hex() {
  // @@protoc_insertion_point(field_release:worker.OutputFileMetadata.largest_key_hex)
  
  return largest_key_hex_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void OutputFileMetadata::set_allocated_largest_key_hex(::std::string* largest_key_hex) {
  if (largest_key_hex != NULL) {
    
  } else {
    
  }
  largest_key_hex_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), largest_key_hex);
  // @@protoc_insertion_point(field_set_allocated:worker.OutputFileMetadata.largest_key_hex)
}

// uint64 num_entries = 4;
inline void OutputFileMetadata::clear_num_entries() {
  num_entries_ = GOOGLE_ULONGLONG(0);
}
inline ::google::protobuf::uint64 OutputFileMetadata::num_entries() const {
  // @@protoc_insertion_point(field_get:worker.OutputFileMetadata.num_entries)
  return num_entries_;
}
inline void OutputFileMetadata::set_num_entries(::google::protobuf::uint64 value) {
  
  num_entries_ = value;
  // @@protoc_insertion_point(field_set:worker.OutputFileMetadata.num_entries)
}

// uint64 file_size = 5;
inline void OutputFileMetadata::clear_file_size() {
  file_size_ = GOOGLE_ULONGLONG(0);
}
inline ::google::protobuf::uint64 OutputFileMetadata::file_size() const {
  // @@protoc_insertion_point(field_get:worker.OutputFileMetadata.file_size)
  return file_size_;
}
inline void OutputFileMetadata::set_file_size(::google::protobuf::uint64 value) {
  
  file_size_ = value;
  // @@protoc_insertion_point(field_set:worker.OutputFileMetadata.file_size)
}

// -------------------------------------------------------------------

// CompactionResponse

// bool success = 1;
inline void CompactionResponse::clear_success() {
  success_ = false;
}
inline bool CompactionResponse::success() const {
  // @@protoc_insertion_point(field_get:worker.CompactionResponse.success)
  return success_;
}
inline void CompactionResponse::set_success(bool value) {
  
  success_ = value;
  // @@protoc_insertion_point(field_set:worker.CompactionResponse.success)
}

// string job_id = 2;
inline void CompactionResponse::clear_job_id() {
  job_id_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& CompactionResponse::job_id() const {
  // @@protoc_insertion_point(field_get:worker.CompactionResponse.job_id)
  return job_id_.GetNoArena();
}
inline void CompactionResponse::set_job_id(const ::std::string& value) {
  
  job_id_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:worker.CompactionResponse.job_id)
}
#if LANG_CXX11
inline void CompactionResponse::set_job_id(::std::string&& value) {
  
  job_id_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:worker.CompactionResponse.job_id)
}
#endif
inline void CompactionResponse::set_job_id(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  job_id_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:worker.CompactionResponse.job_id)
}
inline void CompactionResponse::set_job_id(const char* value, size_t size) {
  
  job_id_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:worker.CompactionResponse.job_id)
}
inline ::std::string* CompactionResponse::mutable_job_id() {
  
  // @@protoc_insertion_point(field_mutable:worker.CompactionResponse.job_id)
  return job_id_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* CompactionResponse::release_job_id() {
  // @@protoc_insertion_point(field_release:worker.CompactionResponse.job_id)
  
  return job_id_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void CompactionResponse::set_allocated_job_id(::std::string* job_id) {
  if (job_id != NULL) {
    
  } else {
    
  }
  job_id_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), job_id);
  // @@protoc_insertion_point(field_set_allocated:worker.CompactionResponse.job_id)
}

// repeated string output_sst_files = 3;
inline int CompactionResponse::output_sst_files_size() const {
  return output_sst_files_.size();
}
inline void CompactionResponse::clear_output_sst_files() {
  output_sst_files_.Clear();
}
inline const ::std::string& CompactionResponse::output_sst_files(int index) const {
  // @@protoc_insertion_point(field_get:worker.CompactionResponse.output_sst_files)
  return output_sst_files_.Get(index);
}
inline ::std::string* CompactionResponse::mutable_output_sst_files(int index) {
  // @@protoc_insertion_point(field_mutable:worker.CompactionResponse.output_sst_files)
  return output_sst_files_.Mutable(index);
}
inline void CompactionResponse::set_output_sst_files(int index, const ::std::string& value) {
  // @@protoc_insertion_point(field_set:worker.CompactionResponse.output_sst_files)
  output_sst_files_.Mutable(index)->assign(value);
}
#if LANG_CXX11
inline void CompactionResponse::set_output_sst_files(int index, ::std::string&& value) {
  // @@protoc_insertion_point(field_set:worker.CompactionResponse.output_sst_files)
  output_sst_files_.Mutable(index)->assign(std::move(value));
}
#endif
inline void CompactionResponse::set_output_sst_files(int index, const char* value) {
  GOOGLE_DCHECK(value != NULL);
  output_sst_files_.Mutable(index)->assign(value);
  // @@protoc_insertion_point(field_set_char:worker.CompactionResponse.output_sst_files)
}
inline void CompactionResponse::set_output_sst_files(int index, const char* value, size_t size) {
  output_sst_files_.Mutable(index)->assign(
    reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_set_pointer:worker.CompactionResponse.output_sst_files)
}
inline ::std::string* CompactionResponse::add_output_sst_files() {
  // @@protoc_insertion_point(field_add_mutable:worker.CompactionResponse.output_sst_files)
  return output_sst_files_.Add();
}
inline void CompactionResponse::add_output_sst_files(const ::std::string& value) {
  output_sst_files_.Add()->assign(value);
  // @@protoc_insertion_point(field_add:worker.CompactionResponse.output_sst_files)
}
#if LANG_CXX11
inline void CompactionResponse::add_output_sst_files(::std::string&& value) {
  output_sst_files_.Add(std::move(value));
  // @@protoc_insertion_point(field_add:worker.CompactionResponse.output_sst_files)
}
#endif
inline void CompactionResponse::add_output_sst_files(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  output_sst_files_.Add()->assign(value);
  // @@protoc_insertion_point(field_add_char:worker.CompactionResponse.output_sst_files)
}
inline void CompactionResponse::add_output_sst_files(const char* value, size_t size) {
  output_sst_files_.Add()->assign(reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_add_pointer:worker.CompactionResponse.output_sst_files)
}
inline const ::google::protobuf::RepeatedPtrField< ::std::string>&
CompactionResponse::output_sst_files() const {
  // @@protoc_insertion_point(field_list:worker.CompactionResponse.output_sst_files)
  return output_sst_files_;
}
inline ::google::protobuf::RepeatedPtrField< ::std::string>*
CompactionResponse::mutable_output_sst_files() {
  // @@protoc_insertion_point(field_mutable_list:worker.CompactionResponse.output_sst_files)
  return &output_sst_files_;
}

// uint64 input_size_bytes = 4;
inline void CompactionResponse::clear_input_size_bytes() {
  input_size_bytes_ = GOOGLE_ULONGLONG(0);
}
inline ::google::protobuf::uint64 CompactionResponse::input_size_bytes() const {
  // @@protoc_insertion_point(field_get:worker.CompactionResponse.input_size_bytes)
  return input_size_bytes_;
}
inline void CompactionResponse::set_input_size_bytes(::google::protobuf::uint64 value) {
  
  input_size_bytes_ = value;
  // @@protoc_insertion_point(field_set:worker.CompactionResponse.input_size_bytes)
}

// uint64 output_size_bytes = 5;
inline void CompactionResponse::clear_output_size_bytes() {
  output_size_bytes_ = GOOGLE_ULONGLONG(0);
}
inline ::google::protobuf::uint64 CompactionResponse::output_size_bytes() const {
  // @@protoc_insertion_point(field_get:worker.CompactionResponse.output_size_bytes)
  return output_size_bytes_;
}
inline void CompactionResponse::set_output_size_bytes(::google::protobuf::uint64 value) {
  
  output_size_bytes_ = value;
  // @@protoc_insertion_point(field_set:worker.CompactionResponse.output_size_bytes)
}

// double compression_ratio = 6;
inline void CompactionResponse::clear_compression_ratio() {
  compression_ratio_ = 0;
}
inline double CompactionResponse::compression_ratio() const {
  // @@protoc_insertion_point(field_get:worker.CompactionResponse.compression_ratio)
  return compression_ratio_;
}
inline void CompactionResponse::set_compression_ratio(double value) {
  
  compression_ratio_ = value;
  // @@protoc_insertion_point(field_set:worker.CompactionResponse.compression_ratio)
}

// uint64 processing_time_ms = 7;
inline void CompactionResponse::clear_processing_time_ms() {
  processing_time_ms_ = GOOGLE_ULONGLONG(0);
}
inline ::google::protobuf::uint64 CompactionResponse::processing_time_ms() const {
  // @@protoc_insertion_point(field_get:worker.CompactionResponse.processing_time_ms)
  return processing_time_ms_;
}
inline void CompactionResponse::set_processing_time_ms(::google::protobuf::uint64 value) {
  
  processing_time_ms_ = value;
  // @@protoc_insertion_point(field_set:worker.CompactionResponse.processing_time_ms)
}

// string error_message = 8;
inline void CompactionResponse::clear_error_message() {
  error_message_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& CompactionResponse::error_message() const {
  // @@protoc_insertion_point(field_get:worker.CompactionResponse.error_message)
  return error_message_.GetNoArena();
}
inline void CompactionResponse::set_error_message(const ::std::string& value) {
  
  error_message_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:worker.CompactionResponse.error_message)
}
#if LANG_CXX11
inline void CompactionResponse::set_error_message(::std::string&& value) {
  
  error_message_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:worker.CompactionResponse.error_message)
}
#endif
inline void CompactionResponse::set_error_message(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  error_message_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:worker.CompactionResponse.error_message)
}
inline void CompactionResponse::set_error_message(const char* value, size_t size) {
  
  error_message_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:worker.CompactionResponse.error_message)
}
inline ::std::string* CompactionResponse::mutable_error_message() {
  
  // @@protoc_insertion_point(field_mutable:worker.CompactionResponse.error_message)
  return error_message_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* CompactionResponse::release_error_message() {
  // @@protoc_insertion_point(field_release:worker.CompactionResponse.error_message)
  
  return error_message_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void CompactionResponse::set_allocated_error_message(::std::string* error_message) {
  if (error_message != NULL) {
    
  } else {
    
  }
  error_message_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), error_message);
  // @@protoc_insertion_point(field_set_allocated:worker.CompactionResponse.error_message)
}

// string smallest_key = 9;
inline void CompactionResponse::clear_smallest_key() {
  smallest_key_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& CompactionResponse::smallest_key() const {
  // @@protoc_insertion_point(field_get:worker.CompactionResponse.smallest_key)
  return smallest_key_.GetNoArena();
}
inline void CompactionResponse::set_smallest_key(const ::std::string& value) {
  
  smallest_key_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:worker.CompactionResponse.smallest_key)
}
#if LANG_CXX11
inline void CompactionResponse::set_smallest_key(::std::string&& value) {
  
  smallest_key_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:worker.CompactionResponse.smallest_key)
}
#endif
inline void CompactionResponse::set_smallest_key(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  smallest_key_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:worker.CompactionResponse.smallest_key)
}
inline void CompactionResponse::set_smallest_key(const char* value, size_t size) {
  
  smallest_key_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:worker.CompactionResponse.smallest_key)
}
inline ::std::string* CompactionResponse::mutable_smallest_key() {
  
  // @@protoc_insertion_point(field_mutable:worker.CompactionResponse.smallest_key)
  return smallest_key_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* CompactionResponse::release_smallest_key() {
  // @@protoc_insertion_point(field_release:worker.CompactionResponse.smallest_key)
  
  return smallest_key_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void CompactionResponse::set_allocated_smallest_key(::std::string* smallest_key) {
  if (smallest_key != NULL) {
    
  } else {
    
  }
  smallest_key_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), smallest_key);
  // @@protoc_insertion_point(field_set_allocated:worker.CompactionResponse.smallest_key)
}

// string largest_key = 10;
inline void CompactionResponse::clear_largest_key() {
  largest_key_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& CompactionResponse::largest_key() const {
  // @@protoc_insertion_point(field_get:worker.CompactionResponse.largest_key)
  return largest_key_.GetNoArena();
}
inline void CompactionResponse::set_largest_key(const ::std::string& value) {
  
  largest_key_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:worker.CompactionResponse.largest_key)
}
#if LANG_CXX11
inline void CompactionResponse::set_largest_key(::std::string&& value) {
  
  largest_key_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:worker.CompactionResponse.largest_key)
}
#endif
inline void CompactionResponse::set_largest_key(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  largest_key_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:worker.CompactionResponse.largest_key)
}
inline void CompactionResponse::set_largest_key(const char* value, size_t size) {
  
  largest_key_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:worker.CompactionResponse.largest_key)
}
inline ::std::string* CompactionResponse::mutable_largest_key() {
  
  // @@protoc_insertion_point(field_mutable:worker.CompactionResponse.largest_key)
  return largest_key_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* CompactionResponse::release_largest_key() {
  // @@protoc_insertion_point(field_release:worker.CompactionResponse.largest_key)
  
  return largest_key_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void CompactionResponse::set_allocated_largest_key(::std::string* largest_key) {
  if (largest_key != NULL) {
    
  } else {
    
  }
  largest_key_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), largest_key);
  // @@protoc_insertion_point(field_set_allocated:worker.CompactionResponse.largest_key)
}

// uint64 num_entries = 11;
inline void CompactionResponse::clear_num_entries() {
  num_entries_ = GOOGLE_ULONGLONG(0);
}
inline ::google::protobuf::uint64 CompactionResponse::num_entries() const {
  // @@protoc_insertion_point(field_get:worker.CompactionResponse.num_entries)
  return num_entries_;
}
inline void CompactionResponse::set_num_entries(::google::protobuf::uint64 value) {
  
  num_entries_ = value;
  // @@protoc_insertion_point(field_set:worker.CompactionResponse.num_entries)
}

// uint64 file_size = 12;
inline void CompactionResponse::clear_file_size() {
  file_size_ = GOOGLE_ULONGLONG(0);
}
inline ::google::protobuf::uint64 CompactionResponse::file_size() const {
  // @@protoc_insertion_point(field_get:worker.CompactionResponse.file_size)
  return file_size_;
}
inline void CompactionResponse::set_file_size(::google::protobuf::uint64 value) {
  
  file_size_ = value;
  // @@protoc_insertion_point(field_set:worker.CompactionResponse.file_size)
}

// uint64 num_input_entries = 13;
inline void CompactionResponse::clear_num_input_entries() {
  num_input_entries_ = GOOGLE_ULONGLONG(0);
}
inline ::google::protobuf::uint64 CompactionResponse::num_input_entries() const {
  // @@protoc_insertion_point(field_get:worker.CompactionResponse.num_input_entries)
  return num_input_entries_;
}
inline void CompactionResponse::set_num_input_entries(::google::protobuf::uint64 value) {
  
  num_input_entries_ = value;
  // @@protoc_insertion_point(field_set:worker.CompactionResponse.num_input_entries)
}

// repeated .worker.OutputFileMetadata output_file_metadata = 14;
inline int CompactionResponse::output_file_metadata_size() const {
  return output_file_metadata_.size();
}
inline void CompactionResponse::clear_output_file_metadata() {
  output_file_metadata_.Clear();
}
inline ::worker::OutputFileMetadata* CompactionResponse::mutable_output_file_metadata(int index) {
  // @@protoc_insertion_point(field_mutable:worker.CompactionResponse.output_file_metadata)
  return output_file_metadata_.Mutable(index);
}
inline ::google::protobuf::RepeatedPtrField< ::worker::OutputFileMetadata >*
CompactionResponse::mutable_output_file_metadata() {
  // @@protoc_insertion_point(field_mutable_list:worker.CompactionResponse.output_file_metadata)
  return &output_file_metadata_;
}
inline const ::worker::OutputFileMetadata& CompactionResponse::output_file_metadata(int index) const {
  // @@protoc_insertion_point(field_get:worker.CompactionResponse.output_file_metadata)
  return output_file_metadata_.Get(index);
}
inline ::worker::OutputFileMetadata* CompactionResponse::add_output_file_metadata() {
  // @@protoc_insertion_point(field_add:worker.CompactionResponse.output_file_metadata)
  return output_file_metadata_.Add();
}
inline const ::google::protobuf::RepeatedPtrField< ::worker::OutputFileMetadata >&
CompactionResponse::output_file_metadata() const {
  // @@protoc_insertion_point(field_list:worker.CompactionResponse.output_file_metadata)
  return output_file_metadata_;
}

// -------------------------------------------------------------------

// StatusRequest

// -------------------------------------------------------------------

// StatusResponse

// string node_name = 1;
inline void StatusResponse::clear_node_name() {
  node_name_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& StatusResponse::node_name() const {
  // @@protoc_insertion_point(field_get:worker.StatusResponse.node_name)
  return node_name_.GetNoArena();
}
inline void StatusResponse::set_node_name(const ::std::string& value) {
  
  node_name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:worker.StatusResponse.node_name)
}
#if LANG_CXX11
inline void StatusResponse::set_node_name(::std::string&& value) {
  
  node_name_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:worker.StatusResponse.node_name)
}
#endif
inline void StatusResponse::set_node_name(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  node_name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:worker.StatusResponse.node_name)
}
inline void StatusResponse::set_node_name(const char* value, size_t size) {
  
  node_name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:worker.StatusResponse.node_name)
}
inline ::std::string* StatusResponse::mutable_node_name() {
  
  // @@protoc_insertion_point(field_mutable:worker.StatusResponse.node_name)
  return node_name_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* StatusResponse::release_node_name() {
  // @@protoc_insertion_point(field_release:worker.StatusResponse.node_name)
  
  return node_name_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void StatusResponse::set_allocated_node_name(::std::string* node_name) {
  if (node_name != NULL) {
    
  } else {
    
  }
  node_name_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), node_name);
  // @@protoc_insertion_point(field_set_allocated:worker.StatusResponse.node_name)
}

// bool is_healthy = 2;
inline void StatusResponse::clear_is_healthy() {
  is_healthy_ = false;
}
inline bool StatusResponse::is_healthy() const {
  // @@protoc_insertion_point(field_get:worker.StatusResponse.is_healthy)
  return is_healthy_;
}
inline void StatusResponse::set_is_healthy(bool value) {
  
  is_healthy_ = value;
  // @@protoc_insertion_point(field_set:worker.StatusResponse.is_healthy)
}

// int32 active_jobs = 3;
inline void StatusResponse::clear_active_jobs() {
  active_jobs_ = 0;
}
inline ::google::protobuf::int32 StatusResponse::active_jobs() const {
  // @@protoc_insertion_point(field_get:worker.StatusResponse.active_jobs)
  return active_jobs_;
}
inline void StatusResponse::set_active_jobs(::google::protobuf::int32 value) {
  
  active_jobs_ = value;
  // @@protoc_insertion_point(field_set:worker.StatusResponse.active_jobs)
}

// int32 total_completed = 4;
inline void StatusResponse::clear_total_completed() {
  total_completed_ = 0;
}
inline ::google::protobuf::int32 StatusResponse::total_completed() const {
  // @@protoc_insertion_point(field_get:worker.StatusResponse.total_completed)
  return total_completed_;
}
inline void StatusResponse::set_total_completed(::google::protobuf::int32 value) {
  
  total_completed_ = value;
  // @@protoc_insertion_point(field_set:worker.StatusResponse.total_completed)
}

// int64 avg_processing_time_ms = 5;
inline void StatusResponse::clear_avg_processing_time_ms() {
  avg_processing_time_ms_ = GOOGLE_LONGLONG(0);
}
inline ::google::protobuf::int64 StatusResponse::avg_processing_time_ms() const {
  // @@protoc_insertion_point(field_get:worker.StatusResponse.avg_processing_time_ms)
  return avg_processing_time_ms_;
}
inline void StatusResponse::set_avg_processing_time_ms(::google::protobuf::int64 value) {
  
  avg_processing_time_ms_ = value;
  // @@protoc_insertion_point(field_set:worker.StatusResponse.avg_processing_time_ms)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace worker

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_INCLUDED_worker_5fservice_2eproto
