# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

  config.vm.define "linux32" do |linux32|
    linux32.vm.box = "ubuntu/trusty32"
    linux32.vm.provision :shell, path: "build-linux.sh"
  end

  config.vm.define "linux64" do |linux64|
    linux64.vm.box = "ubuntu/trusty64"
    linux64.vm.provision :shell, path: "build-linux.sh"
  end

  config.vm.provider "virtualbox" do |v|
    v.memory = 2048
    v.cpus = 4
  end

  config.vm.synced_folder "../", "/rocksdb-build"
  config.vm.synced_folder "../..", "/rocksdb", type: "rsync"
end
