# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: worker_service.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'worker_service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14worker_service.proto\x12\x06worker\"h\n\x11\x43ompactionRequest\x12\x0e\n\x06job_id\x18\x01 \x01(\t\x12\x17\n\x0finput_sst_files\x18\x02 \x03(\t\x12*\n\x07options\x18\x03 \x01(\x0b\x32\x19.worker.CompactionOptions\"b\n\x11\x43ompactionOptions\x12\x18\n\x10\x63ompression_type\x18\x01 \x01(\t\x12\x18\n\x10target_file_size\x18\x02 \x01(\x04\x12\x19\n\x11\x65nable_statistics\x18\x03 \x01(\x08\"\x82\x01\n\x12OutputFileMetadata\x12\x11\n\tfile_path\x18\x01 \x01(\t\x12\x18\n\x10smallest_key_hex\x18\x02 \x01(\t\x12\x17\n\x0flargest_key_hex\x18\x03 \x01(\t\x12\x13\n\x0bnum_entries\x18\x04 \x01(\x04\x12\x11\n\tfile_size\x18\x05 \x01(\x04\"\xfa\x02\n\x12\x43ompactionResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0e\n\x06job_id\x18\x02 \x01(\t\x12\x18\n\x10output_sst_files\x18\x03 \x03(\t\x12\x18\n\x10input_size_bytes\x18\x04 \x01(\x04\x12\x19\n\x11output_size_bytes\x18\x05 \x01(\x04\x12\x19\n\x11\x63ompression_ratio\x18\x06 \x01(\x01\x12\x1a\n\x12processing_time_ms\x18\x07 \x01(\x04\x12\x15\n\rerror_message\x18\x08 \x01(\t\x12\x14\n\x0csmallest_key\x18\t \x01(\t\x12\x13\n\x0blargest_key\x18\n \x01(\t\x12\x13\n\x0bnum_entries\x18\x0b \x01(\x04\x12\x11\n\tfile_size\x18\x0c \x01(\x04\x12\x19\n\x11num_input_entries\x18\r \x01(\x04\x12\x38\n\x14output_file_metadata\x18\x0e \x03(\x0b\x32\x1a.worker.OutputFileMetadata\"\x0f\n\rStatusRequest\"\x85\x01\n\x0eStatusResponse\x12\x11\n\tnode_name\x18\x01 \x01(\t\x12\x12\n\nis_healthy\x18\x02 \x01(\x08\x12\x13\n\x0b\x61\x63tive_jobs\x18\x03 \x01(\x05\x12\x17\n\x0ftotal_completed\x18\x04 \x01(\x05\x12\x1e\n\x16\x61vg_processing_time_ms\x18\x05 \x01(\x03\x32\xa7\x01\n\x17\x43ompactionWorkerService\x12J\n\x11PerformCompaction\x12\x19.worker.CompactionRequest\x1a\x1a.worker.CompactionResponse\x12@\n\x0fGetWorkerStatus\x12\x15.worker.StatusRequest\x1a\x16.worker.StatusResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'worker_service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_COMPACTIONREQUEST']._serialized_start=32
  _globals['_COMPACTIONREQUEST']._serialized_end=136
  _globals['_COMPACTIONOPTIONS']._serialized_start=138
  _globals['_COMPACTIONOPTIONS']._serialized_end=236
  _globals['_OUTPUTFILEMETADATA']._serialized_start=239
  _globals['_OUTPUTFILEMETADATA']._serialized_end=369
  _globals['_COMPACTIONRESPONSE']._serialized_start=372
  _globals['_COMPACTIONRESPONSE']._serialized_end=750
  _globals['_STATUSREQUEST']._serialized_start=752
  _globals['_STATUSREQUEST']._serialized_end=767
  _globals['_STATUSRESPONSE']._serialized_start=770
  _globals['_STATUSRESPONSE']._serialized_end=903
  _globals['_COMPACTIONWORKERSERVICE']._serialized_start=906
  _globals['_COMPACTIONWORKERSERVICE']._serialized_end=1073
# @@protoc_insertion_point(module_scope)
