/**
 * Autogenerated by Thrift
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "leveldb_constants.h"

namespace Tleveldb {

const leveldbConstants g_leveldb_constants;

leveldbConstants::leveldbConstants() {
}

} // namespace

