name: install-maven
runs:
  using: composite
  steps:
  - name: Install Maven
    run: |
      wget --no-check-certificate https://dlcdn.apache.org/maven/maven-3/3.9.10/binaries/apache-maven-3.9.10-bin.tar.gz
      tar zxf apache-maven-3.9.10-bin.tar.gz
      echo "export M2_HOME=$(pwd)/apache-maven-3.9.10" >> $GITHUB_ENV
      echo "$(pwd)/apache-maven-3.9.10/bin" >> $GITHUB_PATH
    shell: bash
