name: install-maven
runs:
  using: composite
  steps:
  - name: Install Maven
    run: |
      wget --no-check-certificate https://archive.apache.org/dist/maven/maven-3/3.9.11/binaries/apache-maven-3.9.11-bin.tar.gz
      tar zxf apache-maven-3.9.11-bin.tar.gz
      echo "export M2_HOME=$(pwd)/apache-maven-3.9.11" >> $GITHUB_ENV
      echo "$(pwd)/apache-maven-3.9.11/bin" >> $GITHUB_PATH
    shell: bash
