// Copyright (c) 2011-present, Facebook, Inc.  All rights reserved.
//  This source code is licensed under both the GPLv2 (found in the
//  COPYING file in the root directory) and Apache 2.0 License
//  (found in the LICENSE.Apache file in the root directory).

// This file is designed for caching those frequently used IDs and provide
// efficient portal (i.e, a set of static functions) to access java code
// from c++.

#pragma once

#include <jni.h>

#include "rocksdb/db.h"
#include "rocksdb/status.h"
#include "rocksjni/portal/common.h"

namespace ROCKSDB_NAMESPACE {
// The portal class for org.rocksdb.TickerType
class TickerTypeJni {
 public:
  // Returns the equivalent org.rocksdb.TickerType for the provided
  // C++ ROCKSDB_NAMESPACE::Tickers enum
  static jbyte toJavaTickerType(const ROCKSDB_NAMESPACE::Tickers& tickers) {
    switch (tickers) {
      case ROCKSDB_NAMESPACE::Tickers::BLOCK_CACHE_MISS:
        return 0x0;
      case ROCKSDB_NAMESPACE::Tickers::BLOCK_CACHE_HIT:
        return 0x1;
      case ROCKSDB_NAMESPACE::Tickers::BLOCK_CACHE_ADD:
        return 0x2;
      case ROCKSDB_NAMESPACE::Tickers::BLOCK_CACHE_ADD_FAILURES:
        return 0x3;
      case ROCKSDB_NAMESPACE::Tickers::BLOCK_CACHE_INDEX_MISS:
        return 0x4;
      case ROCKSDB_NAMESPACE::Tickers::BLOCK_CACHE_INDEX_HIT:
        return 0x5;
      case ROCKSDB_NAMESPACE::Tickers::BLOCK_CACHE_INDEX_ADD:
        return 0x6;
      case ROCKSDB_NAMESPACE::Tickers::BLOCK_CACHE_INDEX_BYTES_INSERT:
        return 0x7;
      case ROCKSDB_NAMESPACE::Tickers::BLOCK_CACHE_FILTER_MISS:
        return 0x8;
      case ROCKSDB_NAMESPACE::Tickers::BLOCK_CACHE_FILTER_HIT:
        return 0x9;
      case ROCKSDB_NAMESPACE::Tickers::BLOCK_CACHE_FILTER_ADD:
        return 0xA;
      case ROCKSDB_NAMESPACE::Tickers::BLOCK_CACHE_FILTER_BYTES_INSERT:
        return 0xB;
      case ROCKSDB_NAMESPACE::Tickers::BLOCK_CACHE_DATA_MISS:
        return 0xC;
      case ROCKSDB_NAMESPACE::Tickers::BLOCK_CACHE_DATA_HIT:
        return 0xD;
      case ROCKSDB_NAMESPACE::Tickers::BLOCK_CACHE_DATA_ADD:
        return 0xE;
      case ROCKSDB_NAMESPACE::Tickers::BLOCK_CACHE_DATA_BYTES_INSERT:
        return 0xF;
      case ROCKSDB_NAMESPACE::Tickers::BLOCK_CACHE_BYTES_READ:
        return 0x10;
      case ROCKSDB_NAMESPACE::Tickers::BLOCK_CACHE_BYTES_WRITE:
        return 0x11;
      case ROCKSDB_NAMESPACE::Tickers::BLOCK_CACHE_COMPRESSION_DICT_MISS:
        return 0x12;
      case ROCKSDB_NAMESPACE::Tickers::BLOCK_CACHE_COMPRESSION_DICT_HIT:
        return 0x13;
      case ROCKSDB_NAMESPACE::Tickers::BLOCK_CACHE_COMPRESSION_DICT_ADD:
        return 0x14;
      case ROCKSDB_NAMESPACE::Tickers::
          BLOCK_CACHE_COMPRESSION_DICT_BYTES_INSERT:
        return 0x15;
      case ROCKSDB_NAMESPACE::Tickers::BLOCK_CACHE_ADD_REDUNDANT:
        return 0x16;
      case ROCKSDB_NAMESPACE::Tickers::BLOCK_CACHE_INDEX_ADD_REDUNDANT:
        return 0x17;
      case ROCKSDB_NAMESPACE::Tickers::BLOCK_CACHE_FILTER_ADD_REDUNDANT:
        return 0x18;
      case ROCKSDB_NAMESPACE::Tickers::BLOCK_CACHE_DATA_ADD_REDUNDANT:
        return 0x19;
      case ROCKSDB_NAMESPACE::Tickers::
          BLOCK_CACHE_COMPRESSION_DICT_ADD_REDUNDANT:
        return 0x1A;
      case ROCKSDB_NAMESPACE::Tickers::SECONDARY_CACHE_HITS:
        return 0x1B;
      case ROCKSDB_NAMESPACE::Tickers::SECONDARY_CACHE_FILTER_HITS:
        return 0x1C;
      case ROCKSDB_NAMESPACE::Tickers::SECONDARY_CACHE_INDEX_HITS:
        return 0x1D;
      case ROCKSDB_NAMESPACE::Tickers::SECONDARY_CACHE_DATA_HITS:
        return 0x1E;
      case ROCKSDB_NAMESPACE::Tickers::COMPRESSED_SECONDARY_CACHE_DUMMY_HITS:
        return 0x1F;
      case ROCKSDB_NAMESPACE::Tickers::COMPRESSED_SECONDARY_CACHE_HITS:
        return 0x20;
      case ROCKSDB_NAMESPACE::Tickers::COMPRESSED_SECONDARY_CACHE_PROMOTIONS:
        return 0x21;
      case ROCKSDB_NAMESPACE::Tickers::
          COMPRESSED_SECONDARY_CACHE_PROMOTION_SKIPS:
        return 0x22;
      case ROCKSDB_NAMESPACE::Tickers::BLOOM_FILTER_USEFUL:
        return 0x23;
      case ROCKSDB_NAMESPACE::Tickers::BLOOM_FILTER_FULL_POSITIVE:
        return 0x24;
      case ROCKSDB_NAMESPACE::Tickers::BLOOM_FILTER_FULL_TRUE_POSITIVE:
        return 0x25;
      case ROCKSDB_NAMESPACE::Tickers::BLOOM_FILTER_PREFIX_CHECKED:
        return 0x26;
      case ROCKSDB_NAMESPACE::Tickers::BLOOM_FILTER_PREFIX_USEFUL:
        return 0x27;
      case ROCKSDB_NAMESPACE::Tickers::BLOOM_FILTER_PREFIX_TRUE_POSITIVE:
        return 0x28;
      case ROCKSDB_NAMESPACE::Tickers::PERSISTENT_CACHE_HIT:
        return 0x29;
      case ROCKSDB_NAMESPACE::Tickers::PERSISTENT_CACHE_MISS:
        return 0x2A;
      case ROCKSDB_NAMESPACE::Tickers::SIM_BLOCK_CACHE_HIT:
        return 0x2B;
      case ROCKSDB_NAMESPACE::Tickers::SIM_BLOCK_CACHE_MISS:
        return 0x2C;
      case ROCKSDB_NAMESPACE::Tickers::MEMTABLE_HIT:
        return 0x2D;
      case ROCKSDB_NAMESPACE::Tickers::MEMTABLE_MISS:
        return 0x2E;
      case ROCKSDB_NAMESPACE::Tickers::GET_HIT_L0:
        return 0x2F;
      case ROCKSDB_NAMESPACE::Tickers::GET_HIT_L1:
        return 0x30;
      case ROCKSDB_NAMESPACE::Tickers::GET_HIT_L2_AND_UP:
        return 0x31;
      case ROCKSDB_NAMESPACE::Tickers::COMPACTION_KEY_DROP_NEWER_ENTRY:
        return 0x32;
      case ROCKSDB_NAMESPACE::Tickers::COMPACTION_KEY_DROP_OBSOLETE:
        return 0x33;
      case ROCKSDB_NAMESPACE::Tickers::COMPACTION_KEY_DROP_RANGE_DEL:
        return 0x34;
      case ROCKSDB_NAMESPACE::Tickers::COMPACTION_KEY_DROP_USER:
        return 0x35;
      case ROCKSDB_NAMESPACE::Tickers::COMPACTION_RANGE_DEL_DROP_OBSOLETE:
        return 0x36;
      case ROCKSDB_NAMESPACE::Tickers::COMPACTION_OPTIMIZED_DEL_DROP_OBSOLETE:
        return 0x37;
      case ROCKSDB_NAMESPACE::Tickers::COMPACTION_CANCELLED:
        return 0x38;
      case ROCKSDB_NAMESPACE::Tickers::NUMBER_KEYS_WRITTEN:
        return 0x39;
      case ROCKSDB_NAMESPACE::Tickers::NUMBER_KEYS_READ:
        return 0x3A;
      case ROCKSDB_NAMESPACE::Tickers::NUMBER_KEYS_UPDATED:
        return 0x3B;
      case ROCKSDB_NAMESPACE::Tickers::BYTES_WRITTEN:
        return 0x3C;
      case ROCKSDB_NAMESPACE::Tickers::BYTES_READ:
        return 0x3D;
      case ROCKSDB_NAMESPACE::Tickers::NUMBER_DB_SEEK:
        return 0x3E;
      case ROCKSDB_NAMESPACE::Tickers::NUMBER_DB_NEXT:
        return 0x3F;
      case ROCKSDB_NAMESPACE::Tickers::NUMBER_DB_PREV:
        return 0x40;
      case ROCKSDB_NAMESPACE::Tickers::NUMBER_DB_SEEK_FOUND:
        return 0x41;
      case ROCKSDB_NAMESPACE::Tickers::NUMBER_DB_NEXT_FOUND:
        return 0x42;
      case ROCKSDB_NAMESPACE::Tickers::NUMBER_DB_PREV_FOUND:
        return 0x43;
      case ROCKSDB_NAMESPACE::Tickers::ITER_BYTES_READ:
        return 0x44;
      case ROCKSDB_NAMESPACE::Tickers::NUMBER_ITER_SKIP:
        return 0x45;
      case ROCKSDB_NAMESPACE::Tickers::NUMBER_OF_RESEEKS_IN_ITERATION:
        return 0x46;
      case ROCKSDB_NAMESPACE::Tickers::NO_ITERATOR_CREATED:
        return 0x47;
      case ROCKSDB_NAMESPACE::Tickers::NO_ITERATOR_DELETED:
        return 0x48;
      case ROCKSDB_NAMESPACE::Tickers::NO_FILE_OPENS:
        return 0x49;
      case ROCKSDB_NAMESPACE::Tickers::NO_FILE_ERRORS:
        return 0x4A;
      case ROCKSDB_NAMESPACE::Tickers::STALL_MICROS:
        return 0x4B;
      case ROCKSDB_NAMESPACE::Tickers::DB_MUTEX_WAIT_MICROS:
        return 0x4C;
      case ROCKSDB_NAMESPACE::Tickers::NUMBER_MULTIGET_CALLS:
        return 0x4D;
      case ROCKSDB_NAMESPACE::Tickers::NUMBER_MULTIGET_KEYS_READ:
        return 0x4E;
      case ROCKSDB_NAMESPACE::Tickers::NUMBER_MULTIGET_BYTES_READ:
        return 0x4F;
      case ROCKSDB_NAMESPACE::Tickers::NUMBER_MULTIGET_KEYS_FOUND:
        return 0x50;
      case ROCKSDB_NAMESPACE::Tickers::NUMBER_MERGE_FAILURES:
        return 0x51;
      case ROCKSDB_NAMESPACE::Tickers::GET_UPDATES_SINCE_CALLS:
        return 0x52;
      case ROCKSDB_NAMESPACE::Tickers::WAL_FILE_SYNCED:
        return 0x53;
      case ROCKSDB_NAMESPACE::Tickers::WAL_FILE_BYTES:
        return 0x54;
      case ROCKSDB_NAMESPACE::Tickers::WRITE_DONE_BY_SELF:
        return 0x55;
      case ROCKSDB_NAMESPACE::Tickers::WRITE_DONE_BY_OTHER:
        return 0x56;
      case ROCKSDB_NAMESPACE::Tickers::WRITE_WITH_WAL:
        return 0x57;
      case ROCKSDB_NAMESPACE::Tickers::COMPACT_READ_BYTES:
        return 0x58;
      case ROCKSDB_NAMESPACE::Tickers::COMPACT_WRITE_BYTES:
        return 0x59;
      case ROCKSDB_NAMESPACE::Tickers::FLUSH_WRITE_BYTES:
        return 0x5A;
      case ROCKSDB_NAMESPACE::Tickers::COMPACT_READ_BYTES_MARKED:
        return 0x5B;
      case ROCKSDB_NAMESPACE::Tickers::COMPACT_READ_BYTES_PERIODIC:
        return 0x5C;
      case ROCKSDB_NAMESPACE::Tickers::COMPACT_READ_BYTES_TTL:
        return 0x5D;
      case ROCKSDB_NAMESPACE::Tickers::COMPACT_WRITE_BYTES_MARKED:
        return 0x5E;
      case ROCKSDB_NAMESPACE::Tickers::COMPACT_WRITE_BYTES_PERIODIC:
        return 0x5F;
      case ROCKSDB_NAMESPACE::Tickers::COMPACT_WRITE_BYTES_TTL:
        return 0x60;
      case ROCKSDB_NAMESPACE::Tickers::NUMBER_DIRECT_LOAD_TABLE_PROPERTIES:
        return 0x61;
      case ROCKSDB_NAMESPACE::Tickers::NUMBER_SUPERVERSION_ACQUIRES:
        return 0x62;
      case ROCKSDB_NAMESPACE::Tickers::NUMBER_SUPERVERSION_RELEASES:
        return 0x63;
      case ROCKSDB_NAMESPACE::Tickers::NUMBER_SUPERVERSION_CLEANUPS:
        return 0x64;
      case ROCKSDB_NAMESPACE::Tickers::NUMBER_BLOCK_COMPRESSED:
        return 0x65;
      case ROCKSDB_NAMESPACE::Tickers::NUMBER_BLOCK_DECOMPRESSED:
        return 0x66;
      case ROCKSDB_NAMESPACE::Tickers::BYTES_COMPRESSED_FROM:
        return 0x67;
      case ROCKSDB_NAMESPACE::Tickers::BYTES_COMPRESSED_TO:
        return 0x68;
      case ROCKSDB_NAMESPACE::Tickers::BYTES_COMPRESSION_BYPASSED:
        return 0x69;
      case ROCKSDB_NAMESPACE::Tickers::BYTES_COMPRESSION_REJECTED:
        return 0x6A;
      case ROCKSDB_NAMESPACE::Tickers::NUMBER_BLOCK_COMPRESSION_BYPASSED:
        return 0x6B;
      case ROCKSDB_NAMESPACE::Tickers::NUMBER_BLOCK_COMPRESSION_REJECTED:
        return 0x6C;
      case ROCKSDB_NAMESPACE::Tickers::BYTES_DECOMPRESSED_FROM:
        return 0x6D;
      case ROCKSDB_NAMESPACE::Tickers::BYTES_DECOMPRESSED_TO:
        return 0x6E;
      case ROCKSDB_NAMESPACE::Tickers::MERGE_OPERATION_TOTAL_TIME:
        return 0x6F;
      case ROCKSDB_NAMESPACE::Tickers::FILTER_OPERATION_TOTAL_TIME:
        return 0x70;
      case ROCKSDB_NAMESPACE::Tickers::COMPACTION_CPU_TOTAL_TIME:
        return 0x71;
      case ROCKSDB_NAMESPACE::Tickers::ROW_CACHE_HIT:
        return 0x72;
      case ROCKSDB_NAMESPACE::Tickers::ROW_CACHE_MISS:
        return 0x73;
      case ROCKSDB_NAMESPACE::Tickers::READ_AMP_ESTIMATE_USEFUL_BYTES:
        return 0x74;
      case ROCKSDB_NAMESPACE::Tickers::READ_AMP_TOTAL_READ_BYTES:
        return 0x75;
      case ROCKSDB_NAMESPACE::Tickers::NUMBER_RATE_LIMITER_DRAINS:
        return 0x76;
      case ROCKSDB_NAMESPACE::Tickers::BLOB_DB_NUM_PUT:
        return 0x77;
      case ROCKSDB_NAMESPACE::Tickers::BLOB_DB_NUM_WRITE:
        return 0x78;
      case ROCKSDB_NAMESPACE::Tickers::BLOB_DB_NUM_GET:
        return 0x79;
      case ROCKSDB_NAMESPACE::Tickers::BLOB_DB_NUM_MULTIGET:
        return 0x7A;
      case ROCKSDB_NAMESPACE::Tickers::BLOB_DB_NUM_SEEK:
        return 0x7B;
      case ROCKSDB_NAMESPACE::Tickers::BLOB_DB_NUM_NEXT:
        return 0x7C;
      case ROCKSDB_NAMESPACE::Tickers::BLOB_DB_NUM_PREV:
        return 0x7D;
      case ROCKSDB_NAMESPACE::Tickers::BLOB_DB_NUM_KEYS_WRITTEN:
        return 0x7E;
      case ROCKSDB_NAMESPACE::Tickers::BLOB_DB_NUM_KEYS_READ:
        return 0x7F;
      case ROCKSDB_NAMESPACE::Tickers::BLOB_DB_BYTES_WRITTEN:
        return -0x1;
      case ROCKSDB_NAMESPACE::Tickers::BLOB_DB_BYTES_READ:
        return -0x2;
      case ROCKSDB_NAMESPACE::Tickers::BLOB_DB_WRITE_INLINED:
        return -0x3;
      case ROCKSDB_NAMESPACE::Tickers::BLOB_DB_WRITE_INLINED_TTL:
        return -0x4;
      case ROCKSDB_NAMESPACE::Tickers::BLOB_DB_WRITE_BLOB:
        return -0x5;
      case ROCKSDB_NAMESPACE::Tickers::BLOB_DB_WRITE_BLOB_TTL:
        return -0x6;
      case ROCKSDB_NAMESPACE::Tickers::BLOB_DB_BLOB_FILE_BYTES_WRITTEN:
        return -0x7;
      case ROCKSDB_NAMESPACE::Tickers::BLOB_DB_BLOB_FILE_BYTES_READ:
        return -0x8;
      case ROCKSDB_NAMESPACE::Tickers::BLOB_DB_BLOB_FILE_SYNCED:
        return -0x9;
      case ROCKSDB_NAMESPACE::Tickers::BLOB_DB_BLOB_INDEX_EXPIRED_COUNT:
        return -0xA;
      case ROCKSDB_NAMESPACE::Tickers::BLOB_DB_BLOB_INDEX_EXPIRED_SIZE:
        return -0xB;
      case ROCKSDB_NAMESPACE::Tickers::BLOB_DB_BLOB_INDEX_EVICTED_COUNT:
        return -0xC;
      case ROCKSDB_NAMESPACE::Tickers::BLOB_DB_BLOB_INDEX_EVICTED_SIZE:
        return -0xD;
      case ROCKSDB_NAMESPACE::Tickers::BLOB_DB_GC_NUM_FILES:
        return -0xE;
      case ROCKSDB_NAMESPACE::Tickers::BLOB_DB_GC_NUM_NEW_FILES:
        return -0xF;
      case ROCKSDB_NAMESPACE::Tickers::BLOB_DB_GC_FAILURES:
        return -0x10;
      case ROCKSDB_NAMESPACE::Tickers::BLOB_DB_GC_NUM_KEYS_RELOCATED:
        return -0x11;
      case ROCKSDB_NAMESPACE::Tickers::BLOB_DB_GC_BYTES_RELOCATED:
        return -0x12;
      case ROCKSDB_NAMESPACE::Tickers::BLOB_DB_FIFO_NUM_FILES_EVICTED:
        return -0x13;
      case ROCKSDB_NAMESPACE::Tickers::BLOB_DB_FIFO_NUM_KEYS_EVICTED:
        return -0x14;
      case ROCKSDB_NAMESPACE::Tickers::BLOB_DB_FIFO_BYTES_EVICTED:
        return -0x15;
      case ROCKSDB_NAMESPACE::Tickers::BLOB_DB_CACHE_MISS:
        return -0x16;
      case ROCKSDB_NAMESPACE::Tickers::BLOB_DB_CACHE_HIT:
        return -0x17;
      case ROCKSDB_NAMESPACE::Tickers::BLOB_DB_CACHE_ADD:
        return -0x18;
      case ROCKSDB_NAMESPACE::Tickers::BLOB_DB_CACHE_ADD_FAILURES:
        return -0x19;
      case ROCKSDB_NAMESPACE::Tickers::BLOB_DB_CACHE_BYTES_READ:
        return -0x1A;
      case ROCKSDB_NAMESPACE::Tickers::BLOB_DB_CACHE_BYTES_WRITE:
        return -0x1B;
      case ROCKSDB_NAMESPACE::Tickers::TXN_PREPARE_MUTEX_OVERHEAD:
        return -0x1C;
      case ROCKSDB_NAMESPACE::Tickers::TXN_OLD_COMMIT_MAP_MUTEX_OVERHEAD:
        return -0x1D;
      case ROCKSDB_NAMESPACE::Tickers::TXN_DUPLICATE_KEY_OVERHEAD:
        return -0x1E;
      case ROCKSDB_NAMESPACE::Tickers::TXN_SNAPSHOT_MUTEX_OVERHEAD:
        return -0x1F;
      case ROCKSDB_NAMESPACE::Tickers::TXN_GET_TRY_AGAIN:
        return -0x20;
      case ROCKSDB_NAMESPACE::Tickers::FILES_MARKED_TRASH:
        return -0x21;
      case ROCKSDB_NAMESPACE::Tickers::FILES_DELETED_FROM_TRASH_QUEUE:
        return -0x22;
      case ROCKSDB_NAMESPACE::Tickers::FILES_DELETED_IMMEDIATELY:
        return -0x23;
      case ROCKSDB_NAMESPACE::Tickers::ERROR_HANDLER_BG_ERROR_COUNT:
        return -0x24;
      case ROCKSDB_NAMESPACE::Tickers::ERROR_HANDLER_BG_IO_ERROR_COUNT:
        return -0x25;
      case ROCKSDB_NAMESPACE::Tickers::
          ERROR_HANDLER_BG_RETRYABLE_IO_ERROR_COUNT:
        return -0x26;
      case ROCKSDB_NAMESPACE::Tickers::ERROR_HANDLER_AUTORESUME_COUNT:
        return -0x27;
      case ROCKSDB_NAMESPACE::Tickers::
          ERROR_HANDLER_AUTORESUME_RETRY_TOTAL_COUNT:
        return -0x28;
      case ROCKSDB_NAMESPACE::Tickers::ERROR_HANDLER_AUTORESUME_SUCCESS_COUNT:
        return -0x29;
      case ROCKSDB_NAMESPACE::Tickers::MEMTABLE_PAYLOAD_BYTES_AT_FLUSH:
        return -0x2A;
      case ROCKSDB_NAMESPACE::Tickers::MEMTABLE_GARBAGE_BYTES_AT_FLUSH:
        return -0x2B;
      case ROCKSDB_NAMESPACE::Tickers::VERIFY_CHECKSUM_READ_BYTES:
        return -0x2C;
      case ROCKSDB_NAMESPACE::Tickers::BACKUP_READ_BYTES:
        return -0x2D;
      case ROCKSDB_NAMESPACE::Tickers::BACKUP_WRITE_BYTES:
        return -0x2E;
      case ROCKSDB_NAMESPACE::Tickers::REMOTE_COMPACT_READ_BYTES:
        return -0x2F;
      case ROCKSDB_NAMESPACE::Tickers::REMOTE_COMPACT_WRITE_BYTES:
        return -0x30;
      case ROCKSDB_NAMESPACE::Tickers::HOT_FILE_READ_BYTES:
        return -0x31;
      case ROCKSDB_NAMESPACE::Tickers::WARM_FILE_READ_BYTES:
        return -0x32;
      case ROCKSDB_NAMESPACE::Tickers::COLD_FILE_READ_BYTES:
        return -0x33;
      case ROCKSDB_NAMESPACE::Tickers::HOT_FILE_READ_COUNT:
        return -0x34;
      case ROCKSDB_NAMESPACE::Tickers::WARM_FILE_READ_COUNT:
        return -0x35;
      case ROCKSDB_NAMESPACE::Tickers::COLD_FILE_READ_COUNT:
        return -0x36;
      case ROCKSDB_NAMESPACE::Tickers::LAST_LEVEL_READ_BYTES:
        return -0x37;
      case ROCKSDB_NAMESPACE::Tickers::LAST_LEVEL_READ_COUNT:
        return -0x38;
      case ROCKSDB_NAMESPACE::Tickers::NON_LAST_LEVEL_READ_BYTES:
        return -0x39;
      case ROCKSDB_NAMESPACE::Tickers::NON_LAST_LEVEL_READ_COUNT:
        return -0x3A;
      case ROCKSDB_NAMESPACE::Tickers::LAST_LEVEL_SEEK_FILTERED:
        return -0x3B;
      case ROCKSDB_NAMESPACE::Tickers::LAST_LEVEL_SEEK_FILTER_MATCH:
        return -0x3C;
      case ROCKSDB_NAMESPACE::Tickers::LAST_LEVEL_SEEK_DATA:
        return -0x3D;
      case ROCKSDB_NAMESPACE::Tickers::LAST_LEVEL_SEEK_DATA_USEFUL_NO_FILTER:
        return -0x3E;
      case ROCKSDB_NAMESPACE::Tickers::LAST_LEVEL_SEEK_DATA_USEFUL_FILTER_MATCH:
        return -0x3F;
      case ROCKSDB_NAMESPACE::Tickers::NON_LAST_LEVEL_SEEK_FILTERED:
        return -0x40;
      case ROCKSDB_NAMESPACE::Tickers::NON_LAST_LEVEL_SEEK_FILTER_MATCH:
        return -0x41;
      case ROCKSDB_NAMESPACE::Tickers::NON_LAST_LEVEL_SEEK_DATA:
        return -0x42;
      case ROCKSDB_NAMESPACE::Tickers::
          NON_LAST_LEVEL_SEEK_DATA_USEFUL_NO_FILTER:
        return -0x43;
      case ROCKSDB_NAMESPACE::Tickers::
          NON_LAST_LEVEL_SEEK_DATA_USEFUL_FILTER_MATCH:
        return -0x44;
      case ROCKSDB_NAMESPACE::Tickers::BLOCK_CHECKSUM_COMPUTE_COUNT:
        return -0x45;
      case ROCKSDB_NAMESPACE::Tickers::BLOCK_CHECKSUM_MISMATCH_COUNT:
        return -0x46;
      case ROCKSDB_NAMESPACE::Tickers::MULTIGET_COROUTINE_COUNT:
        return -0x47;
      case ROCKSDB_NAMESPACE::Tickers::READ_ASYNC_MICROS:
        return -0x48;
      case ROCKSDB_NAMESPACE::Tickers::ASYNC_READ_ERROR_COUNT:
        return -0x49;
      case ROCKSDB_NAMESPACE::Tickers::TABLE_OPEN_PREFETCH_TAIL_MISS:
        return -0x4A;
      case ROCKSDB_NAMESPACE::Tickers::TABLE_OPEN_PREFETCH_TAIL_HIT:
        return -0x4B;
      case ROCKSDB_NAMESPACE::Tickers::TIMESTAMP_FILTER_TABLE_CHECKED:
        return -0x4C;
      case ROCKSDB_NAMESPACE::Tickers::TIMESTAMP_FILTER_TABLE_FILTERED:
        return -0x4D;
      case ROCKSDB_NAMESPACE::Tickers::READAHEAD_TRIMMED:
        return -0x4E;
      case ROCKSDB_NAMESPACE::Tickers::FIFO_MAX_SIZE_COMPACTIONS:
        return -0x4F;
      case ROCKSDB_NAMESPACE::Tickers::FIFO_TTL_COMPACTIONS:
        return -0x50;
      case ROCKSDB_NAMESPACE::Tickers::PREFETCH_BYTES:
        return -0x51;
      case ROCKSDB_NAMESPACE::Tickers::PREFETCH_BYTES_USEFUL:
        return -0x52;
      case ROCKSDB_NAMESPACE::Tickers::PREFETCH_HITS:
        return -0x53;
      case ROCKSDB_NAMESPACE::Tickers::SST_FOOTER_CORRUPTION_COUNT:
        return -0x55;
      case ROCKSDB_NAMESPACE::Tickers::FILE_READ_CORRUPTION_RETRY_COUNT:
        return -0x56;
      case ROCKSDB_NAMESPACE::Tickers::FILE_READ_CORRUPTION_RETRY_SUCCESS_COUNT:
        return -0x57;
      case ROCKSDB_NAMESPACE::Tickers::TICKER_ENUM_MAX:
        // -0x54 is the max value at this time. Since these values are exposed
        // directly to Java clients, we'll keep the value the same till the next
        // major release.
        //
        // TODO: This particular case seems confusing and unnecessary to pin the
        // value since it's meant to be the number of tickers, not an actual
        // ticker value. But we aren't yet in a position to fix it since the
        // number of tickers doesn't fit in the Java representation (jbyte).
        return -0x54;
      default:
        // undefined/default
        return 0x0;
    }
  }

  // Returns the equivalent C++ ROCKSDB_NAMESPACE::Tickers enum for the
  // provided Java org.rocksdb.TickerType
  static ROCKSDB_NAMESPACE::Tickers toCppTickers(jbyte jticker_type) {
    switch (jticker_type) {
      case 0x0:
        return ROCKSDB_NAMESPACE::Tickers::BLOCK_CACHE_MISS;
      case 0x1:
        return ROCKSDB_NAMESPACE::Tickers::BLOCK_CACHE_HIT;
      case 0x2:
        return ROCKSDB_NAMESPACE::Tickers::BLOCK_CACHE_ADD;
      case 0x3:
        return ROCKSDB_NAMESPACE::Tickers::BLOCK_CACHE_ADD_FAILURES;
      case 0x4:
        return ROCKSDB_NAMESPACE::Tickers::BLOCK_CACHE_INDEX_MISS;
      case 0x5:
        return ROCKSDB_NAMESPACE::Tickers::BLOCK_CACHE_INDEX_HIT;
      case 0x6:
        return ROCKSDB_NAMESPACE::Tickers::BLOCK_CACHE_INDEX_ADD;
      case 0x7:
        return ROCKSDB_NAMESPACE::Tickers::BLOCK_CACHE_INDEX_BYTES_INSERT;
      case 0x8:
        return ROCKSDB_NAMESPACE::Tickers::BLOCK_CACHE_FILTER_MISS;
      case 0x9:
        return ROCKSDB_NAMESPACE::Tickers::BLOCK_CACHE_FILTER_HIT;
      case 0xA:
        return ROCKSDB_NAMESPACE::Tickers::BLOCK_CACHE_FILTER_ADD;
      case 0xB:
        return ROCKSDB_NAMESPACE::Tickers::BLOCK_CACHE_FILTER_BYTES_INSERT;
      case 0xC:
        return ROCKSDB_NAMESPACE::Tickers::BLOCK_CACHE_DATA_MISS;
      case 0xD:
        return ROCKSDB_NAMESPACE::Tickers::BLOCK_CACHE_DATA_HIT;
      case 0xE:
        return ROCKSDB_NAMESPACE::Tickers::BLOCK_CACHE_DATA_ADD;
      case 0xF:
        return ROCKSDB_NAMESPACE::Tickers::BLOCK_CACHE_DATA_BYTES_INSERT;
      case 0x10:
        return ROCKSDB_NAMESPACE::Tickers::BLOCK_CACHE_BYTES_READ;
      case 0x11:
        return ROCKSDB_NAMESPACE::Tickers::BLOCK_CACHE_BYTES_WRITE;
      case 0x12:
        return ROCKSDB_NAMESPACE::Tickers::BLOCK_CACHE_COMPRESSION_DICT_MISS;
      case 0x13:
        return ROCKSDB_NAMESPACE::Tickers::BLOCK_CACHE_COMPRESSION_DICT_HIT;
      case 0x14:
        return ROCKSDB_NAMESPACE::Tickers::BLOCK_CACHE_COMPRESSION_DICT_ADD;
      case 0x15:
        return ROCKSDB_NAMESPACE::Tickers::
            BLOCK_CACHE_COMPRESSION_DICT_BYTES_INSERT;
      case 0x16:
        return ROCKSDB_NAMESPACE::Tickers::BLOCK_CACHE_ADD_REDUNDANT;
      case 0x17:
        return ROCKSDB_NAMESPACE::Tickers::BLOCK_CACHE_INDEX_ADD_REDUNDANT;
      case 0x18:
        return ROCKSDB_NAMESPACE::Tickers::BLOCK_CACHE_FILTER_ADD_REDUNDANT;
      case 0x19:
        return ROCKSDB_NAMESPACE::Tickers::BLOCK_CACHE_DATA_ADD_REDUNDANT;
      case 0x1A:
        return ROCKSDB_NAMESPACE::Tickers::
            BLOCK_CACHE_COMPRESSION_DICT_ADD_REDUNDANT;
      case 0x1B:
        return ROCKSDB_NAMESPACE::Tickers::SECONDARY_CACHE_HITS;
      case 0x1C:
        return ROCKSDB_NAMESPACE::Tickers::SECONDARY_CACHE_FILTER_HITS;
      case 0x1D:
        return ROCKSDB_NAMESPACE::Tickers::SECONDARY_CACHE_INDEX_HITS;
      case 0x1E:
        return ROCKSDB_NAMESPACE::Tickers::SECONDARY_CACHE_DATA_HITS;
      case 0x1F:
        return ROCKSDB_NAMESPACE::Tickers::
            COMPRESSED_SECONDARY_CACHE_DUMMY_HITS;
      case 0x20:
        return ROCKSDB_NAMESPACE::Tickers::COMPRESSED_SECONDARY_CACHE_HITS;
      case 0x21:
        return ROCKSDB_NAMESPACE::Tickers::
            COMPRESSED_SECONDARY_CACHE_PROMOTIONS;
      case 0x22:
        return ROCKSDB_NAMESPACE::Tickers::
            COMPRESSED_SECONDARY_CACHE_PROMOTION_SKIPS;
      case 0x23:
        return ROCKSDB_NAMESPACE::Tickers::BLOOM_FILTER_USEFUL;
      case 0x24:
        return ROCKSDB_NAMESPACE::Tickers::BLOOM_FILTER_FULL_POSITIVE;
      case 0x25:
        return ROCKSDB_NAMESPACE::Tickers::BLOOM_FILTER_FULL_TRUE_POSITIVE;
      case 0x26:
        return ROCKSDB_NAMESPACE::Tickers::BLOOM_FILTER_PREFIX_CHECKED;
      case 0x27:
        return ROCKSDB_NAMESPACE::Tickers::BLOOM_FILTER_PREFIX_USEFUL;
      case 0x28:
        return ROCKSDB_NAMESPACE::Tickers::BLOOM_FILTER_PREFIX_TRUE_POSITIVE;
      case 0x29:
        return ROCKSDB_NAMESPACE::Tickers::PERSISTENT_CACHE_HIT;
      case 0x2A:
        return ROCKSDB_NAMESPACE::Tickers::PERSISTENT_CACHE_MISS;
      case 0x2B:
        return ROCKSDB_NAMESPACE::Tickers::SIM_BLOCK_CACHE_HIT;
      case 0x2C:
        return ROCKSDB_NAMESPACE::Tickers::SIM_BLOCK_CACHE_MISS;
      case 0x2D:
        return ROCKSDB_NAMESPACE::Tickers::MEMTABLE_HIT;
      case 0x2E:
        return ROCKSDB_NAMESPACE::Tickers::MEMTABLE_MISS;
      case 0x2F:
        return ROCKSDB_NAMESPACE::Tickers::GET_HIT_L0;
      case 0x30:
        return ROCKSDB_NAMESPACE::Tickers::GET_HIT_L1;
      case 0x31:
        return ROCKSDB_NAMESPACE::Tickers::GET_HIT_L2_AND_UP;
      case 0x32:
        return ROCKSDB_NAMESPACE::Tickers::COMPACTION_KEY_DROP_NEWER_ENTRY;
      case 0x33:
        return ROCKSDB_NAMESPACE::Tickers::COMPACTION_KEY_DROP_OBSOLETE;
      case 0x34:
        return ROCKSDB_NAMESPACE::Tickers::COMPACTION_KEY_DROP_RANGE_DEL;
      case 0x35:
        return ROCKSDB_NAMESPACE::Tickers::COMPACTION_KEY_DROP_USER;
      case 0x36:
        return ROCKSDB_NAMESPACE::Tickers::COMPACTION_RANGE_DEL_DROP_OBSOLETE;
      case 0x37:
        return ROCKSDB_NAMESPACE::Tickers::
            COMPACTION_OPTIMIZED_DEL_DROP_OBSOLETE;
      case 0x38:
        return ROCKSDB_NAMESPACE::Tickers::COMPACTION_CANCELLED;
      case 0x39:
        return ROCKSDB_NAMESPACE::Tickers::NUMBER_KEYS_WRITTEN;
      case 0x3A:
        return ROCKSDB_NAMESPACE::Tickers::NUMBER_KEYS_READ;
      case 0x3B:
        return ROCKSDB_NAMESPACE::Tickers::NUMBER_KEYS_UPDATED;
      case 0x3C:
        return ROCKSDB_NAMESPACE::Tickers::BYTES_WRITTEN;
      case 0x3D:
        return ROCKSDB_NAMESPACE::Tickers::BYTES_READ;
      case 0x3E:
        return ROCKSDB_NAMESPACE::Tickers::NUMBER_DB_SEEK;
      case 0x3F:
        return ROCKSDB_NAMESPACE::Tickers::NUMBER_DB_NEXT;
      case 0x40:
        return ROCKSDB_NAMESPACE::Tickers::NUMBER_DB_PREV;
      case 0x41:
        return ROCKSDB_NAMESPACE::Tickers::NUMBER_DB_SEEK_FOUND;
      case 0x42:
        return ROCKSDB_NAMESPACE::Tickers::NUMBER_DB_NEXT_FOUND;
      case 0x43:
        return ROCKSDB_NAMESPACE::Tickers::NUMBER_DB_PREV_FOUND;
      case 0x44:
        return ROCKSDB_NAMESPACE::Tickers::ITER_BYTES_READ;
      case 0x45:
        return ROCKSDB_NAMESPACE::Tickers::NUMBER_ITER_SKIP;
      case 0x46:
        return ROCKSDB_NAMESPACE::Tickers::NUMBER_OF_RESEEKS_IN_ITERATION;
      case 0x47:
        return ROCKSDB_NAMESPACE::Tickers::NO_ITERATOR_CREATED;
      case 0x48:
        return ROCKSDB_NAMESPACE::Tickers::NO_ITERATOR_DELETED;
      case 0x49:
        return ROCKSDB_NAMESPACE::Tickers::NO_FILE_OPENS;
      case 0x4A:
        return ROCKSDB_NAMESPACE::Tickers::NO_FILE_ERRORS;
      case 0x4B:
        return ROCKSDB_NAMESPACE::Tickers::STALL_MICROS;
      case 0x4C:
        return ROCKSDB_NAMESPACE::Tickers::DB_MUTEX_WAIT_MICROS;
      case 0x4D:
        return ROCKSDB_NAMESPACE::Tickers::NUMBER_MULTIGET_CALLS;
      case 0x4E:
        return ROCKSDB_NAMESPACE::Tickers::NUMBER_MULTIGET_KEYS_READ;
      case 0x4F:
        return ROCKSDB_NAMESPACE::Tickers::NUMBER_MULTIGET_BYTES_READ;
      case 0x50:
        return ROCKSDB_NAMESPACE::Tickers::NUMBER_MULTIGET_KEYS_FOUND;
      case 0x51:
        return ROCKSDB_NAMESPACE::Tickers::NUMBER_MERGE_FAILURES;
      case 0x52:
        return ROCKSDB_NAMESPACE::Tickers::GET_UPDATES_SINCE_CALLS;
      case 0x53:
        return ROCKSDB_NAMESPACE::Tickers::WAL_FILE_SYNCED;
      case 0x54:
        return ROCKSDB_NAMESPACE::Tickers::WAL_FILE_BYTES;
      case 0x55:
        return ROCKSDB_NAMESPACE::Tickers::WRITE_DONE_BY_SELF;
      case 0x56:
        return ROCKSDB_NAMESPACE::Tickers::WRITE_DONE_BY_OTHER;
      case 0x57:
        return ROCKSDB_NAMESPACE::Tickers::WRITE_WITH_WAL;
      case 0x58:
        return ROCKSDB_NAMESPACE::Tickers::COMPACT_READ_BYTES;
      case 0x59:
        return ROCKSDB_NAMESPACE::Tickers::COMPACT_WRITE_BYTES;
      case 0x5A:
        return ROCKSDB_NAMESPACE::Tickers::FLUSH_WRITE_BYTES;
      case 0x5B:
        return ROCKSDB_NAMESPACE::Tickers::COMPACT_READ_BYTES_MARKED;
      case 0x5C:
        return ROCKSDB_NAMESPACE::Tickers::COMPACT_READ_BYTES_PERIODIC;
      case 0x5D:
        return ROCKSDB_NAMESPACE::Tickers::COMPACT_READ_BYTES_TTL;
      case 0x5E:
        return ROCKSDB_NAMESPACE::Tickers::COMPACT_WRITE_BYTES_MARKED;
      case 0x5F:
        return ROCKSDB_NAMESPACE::Tickers::COMPACT_WRITE_BYTES_PERIODIC;
      case 0x60:
        return ROCKSDB_NAMESPACE::Tickers::COMPACT_WRITE_BYTES_TTL;
      case 0x61:
        return ROCKSDB_NAMESPACE::Tickers::NUMBER_DIRECT_LOAD_TABLE_PROPERTIES;
      case 0x62:
        return ROCKSDB_NAMESPACE::Tickers::NUMBER_SUPERVERSION_ACQUIRES;
      case 0x63:
        return ROCKSDB_NAMESPACE::Tickers::NUMBER_SUPERVERSION_RELEASES;
      case 0x64:
        return ROCKSDB_NAMESPACE::Tickers::NUMBER_SUPERVERSION_CLEANUPS;
      case 0x65:
        return ROCKSDB_NAMESPACE::Tickers::NUMBER_BLOCK_COMPRESSED;
      case 0x66:
        return ROCKSDB_NAMESPACE::Tickers::NUMBER_BLOCK_DECOMPRESSED;
      case 0x67:
        return ROCKSDB_NAMESPACE::Tickers::BYTES_COMPRESSED_FROM;
      case 0x68:
        return ROCKSDB_NAMESPACE::Tickers::BYTES_COMPRESSED_TO;
      case 0x69:
        return ROCKSDB_NAMESPACE::Tickers::BYTES_COMPRESSION_BYPASSED;
      case 0x6A:
        return ROCKSDB_NAMESPACE::Tickers::BYTES_COMPRESSION_REJECTED;
      case 0x6B:
        return ROCKSDB_NAMESPACE::Tickers::NUMBER_BLOCK_COMPRESSION_BYPASSED;
      case 0x6C:
        return ROCKSDB_NAMESPACE::Tickers::NUMBER_BLOCK_COMPRESSION_REJECTED;
      case 0x6D:
        return ROCKSDB_NAMESPACE::Tickers::BYTES_DECOMPRESSED_FROM;
      case 0x6E:
        return ROCKSDB_NAMESPACE::Tickers::BYTES_DECOMPRESSED_TO;
      case 0x6F:
        return ROCKSDB_NAMESPACE::Tickers::MERGE_OPERATION_TOTAL_TIME;
      case 0x70:
        return ROCKSDB_NAMESPACE::Tickers::FILTER_OPERATION_TOTAL_TIME;
      case 0x71:
        return ROCKSDB_NAMESPACE::Tickers::COMPACTION_CPU_TOTAL_TIME;
      case 0x72:
        return ROCKSDB_NAMESPACE::Tickers::ROW_CACHE_HIT;
      case 0x73:
        return ROCKSDB_NAMESPACE::Tickers::ROW_CACHE_MISS;
      case 0x74:
        return ROCKSDB_NAMESPACE::Tickers::READ_AMP_ESTIMATE_USEFUL_BYTES;
      case 0x75:
        return ROCKSDB_NAMESPACE::Tickers::READ_AMP_TOTAL_READ_BYTES;
      case 0x76:
        return ROCKSDB_NAMESPACE::Tickers::NUMBER_RATE_LIMITER_DRAINS;
      case 0x77:
        return ROCKSDB_NAMESPACE::Tickers::BLOB_DB_NUM_PUT;
      case 0x78:
        return ROCKSDB_NAMESPACE::Tickers::BLOB_DB_NUM_WRITE;
      case 0x79:
        return ROCKSDB_NAMESPACE::Tickers::BLOB_DB_NUM_GET;
      case 0x7A:
        return ROCKSDB_NAMESPACE::Tickers::BLOB_DB_NUM_MULTIGET;
      case 0x7B:
        return ROCKSDB_NAMESPACE::Tickers::BLOB_DB_NUM_SEEK;
      case 0x7C:
        return ROCKSDB_NAMESPACE::Tickers::BLOB_DB_NUM_NEXT;
      case 0x7D:
        return ROCKSDB_NAMESPACE::Tickers::BLOB_DB_NUM_PREV;
      case 0x7E:
        return ROCKSDB_NAMESPACE::Tickers::BLOB_DB_NUM_KEYS_WRITTEN;
      case 0x7F:
        return ROCKSDB_NAMESPACE::Tickers::BLOB_DB_NUM_KEYS_READ;
      case -0x1:
        return ROCKSDB_NAMESPACE::Tickers::BLOB_DB_BYTES_WRITTEN;
      case -0x2:
        return ROCKSDB_NAMESPACE::Tickers::BLOB_DB_BYTES_READ;
      case -0x3:
        return ROCKSDB_NAMESPACE::Tickers::BLOB_DB_WRITE_INLINED;
      case -0x4:
        return ROCKSDB_NAMESPACE::Tickers::BLOB_DB_WRITE_INLINED_TTL;
      case -0x5:
        return ROCKSDB_NAMESPACE::Tickers::BLOB_DB_WRITE_BLOB;
      case -0x6:
        return ROCKSDB_NAMESPACE::Tickers::BLOB_DB_WRITE_BLOB_TTL;
      case -0x7:
        return ROCKSDB_NAMESPACE::Tickers::BLOB_DB_BLOB_FILE_BYTES_WRITTEN;
      case -0x8:
        return ROCKSDB_NAMESPACE::Tickers::BLOB_DB_BLOB_FILE_BYTES_READ;
      case -0x9:
        return ROCKSDB_NAMESPACE::Tickers::BLOB_DB_BLOB_FILE_SYNCED;
      case -0xA:
        return ROCKSDB_NAMESPACE::Tickers::BLOB_DB_BLOB_INDEX_EXPIRED_COUNT;
      case -0xB:
        return ROCKSDB_NAMESPACE::Tickers::BLOB_DB_BLOB_INDEX_EXPIRED_SIZE;
      case -0xC:
        return ROCKSDB_NAMESPACE::Tickers::BLOB_DB_BLOB_INDEX_EVICTED_COUNT;
      case -0xD:
        return ROCKSDB_NAMESPACE::Tickers::BLOB_DB_BLOB_INDEX_EVICTED_SIZE;
      case -0xE:
        return ROCKSDB_NAMESPACE::Tickers::BLOB_DB_GC_NUM_FILES;
      case -0xF:
        return ROCKSDB_NAMESPACE::Tickers::BLOB_DB_GC_NUM_NEW_FILES;
      case -0x10:
        return ROCKSDB_NAMESPACE::Tickers::BLOB_DB_GC_FAILURES;
      case -0x11:
        return ROCKSDB_NAMESPACE::Tickers::BLOB_DB_GC_NUM_KEYS_RELOCATED;
      case -0x12:
        return ROCKSDB_NAMESPACE::Tickers::BLOB_DB_GC_BYTES_RELOCATED;
      case -0x13:
        return ROCKSDB_NAMESPACE::Tickers::BLOB_DB_FIFO_NUM_FILES_EVICTED;
      case -0x14:
        return ROCKSDB_NAMESPACE::Tickers::BLOB_DB_FIFO_NUM_KEYS_EVICTED;
      case -0x15:
        return ROCKSDB_NAMESPACE::Tickers::BLOB_DB_FIFO_BYTES_EVICTED;
      case -0x16:
        return ROCKSDB_NAMESPACE::Tickers::BLOB_DB_CACHE_MISS;
      case -0x17:
        return ROCKSDB_NAMESPACE::Tickers::BLOB_DB_CACHE_HIT;
      case -0x18:
        return ROCKSDB_NAMESPACE::Tickers::BLOB_DB_CACHE_ADD;
      case -0x19:
        return ROCKSDB_NAMESPACE::Tickers::BLOB_DB_CACHE_ADD_FAILURES;
      case -0x1A:
        return ROCKSDB_NAMESPACE::Tickers::BLOB_DB_CACHE_BYTES_READ;
      case -0x1B:
        return ROCKSDB_NAMESPACE::Tickers::BLOB_DB_CACHE_BYTES_WRITE;
      case -0x1C:
        return ROCKSDB_NAMESPACE::Tickers::TXN_PREPARE_MUTEX_OVERHEAD;
      case -0x1D:
        return ROCKSDB_NAMESPACE::Tickers::TXN_OLD_COMMIT_MAP_MUTEX_OVERHEAD;
      case -0x1E:
        return ROCKSDB_NAMESPACE::Tickers::TXN_DUPLICATE_KEY_OVERHEAD;
      case -0x1F:
        return ROCKSDB_NAMESPACE::Tickers::TXN_SNAPSHOT_MUTEX_OVERHEAD;
      case -0x20:
        return ROCKSDB_NAMESPACE::Tickers::TXN_GET_TRY_AGAIN;
      case -0x21:
        return ROCKSDB_NAMESPACE::Tickers::FILES_MARKED_TRASH;
      case -0x22:
        return ROCKSDB_NAMESPACE::Tickers::FILES_DELETED_FROM_TRASH_QUEUE;
      case -0x23:
        return ROCKSDB_NAMESPACE::Tickers::FILES_DELETED_IMMEDIATELY;
      case -0x24:
        return ROCKSDB_NAMESPACE::Tickers::ERROR_HANDLER_BG_ERROR_COUNT;
      case -0x25:
        return ROCKSDB_NAMESPACE::Tickers::ERROR_HANDLER_BG_IO_ERROR_COUNT;
      case -0x26:
        return ROCKSDB_NAMESPACE::Tickers::
            ERROR_HANDLER_BG_RETRYABLE_IO_ERROR_COUNT;
      case -0x27:
        return ROCKSDB_NAMESPACE::Tickers::ERROR_HANDLER_AUTORESUME_COUNT;
      case -0x28:
        return ROCKSDB_NAMESPACE::Tickers::
            ERROR_HANDLER_AUTORESUME_RETRY_TOTAL_COUNT;
      case -0x29:
        return ROCKSDB_NAMESPACE::Tickers::
            ERROR_HANDLER_AUTORESUME_SUCCESS_COUNT;
      case -0x2A:
        return ROCKSDB_NAMESPACE::Tickers::MEMTABLE_PAYLOAD_BYTES_AT_FLUSH;
      case -0x2B:
        return ROCKSDB_NAMESPACE::Tickers::MEMTABLE_GARBAGE_BYTES_AT_FLUSH;
      case -0x2C:
        return ROCKSDB_NAMESPACE::Tickers::VERIFY_CHECKSUM_READ_BYTES;
      case -0x2D:
        return ROCKSDB_NAMESPACE::Tickers::BACKUP_READ_BYTES;
      case -0x2E:
        return ROCKSDB_NAMESPACE::Tickers::BACKUP_WRITE_BYTES;
      case -0x2F:
        return ROCKSDB_NAMESPACE::Tickers::REMOTE_COMPACT_READ_BYTES;
      case -0x30:
        return ROCKSDB_NAMESPACE::Tickers::REMOTE_COMPACT_WRITE_BYTES;
      case -0x31:
        return ROCKSDB_NAMESPACE::Tickers::HOT_FILE_READ_BYTES;
      case -0x32:
        return ROCKSDB_NAMESPACE::Tickers::WARM_FILE_READ_BYTES;
      case -0x33:
        return ROCKSDB_NAMESPACE::Tickers::COLD_FILE_READ_BYTES;
      case -0x34:
        return ROCKSDB_NAMESPACE::Tickers::HOT_FILE_READ_COUNT;
      case -0x35:
        return ROCKSDB_NAMESPACE::Tickers::WARM_FILE_READ_COUNT;
      case -0x36:
        return ROCKSDB_NAMESPACE::Tickers::COLD_FILE_READ_COUNT;
      case -0x37:
        return ROCKSDB_NAMESPACE::Tickers::LAST_LEVEL_READ_BYTES;
      case -0x38:
        return ROCKSDB_NAMESPACE::Tickers::LAST_LEVEL_READ_COUNT;
      case -0x39:
        return ROCKSDB_NAMESPACE::Tickers::NON_LAST_LEVEL_READ_BYTES;
      case -0x3A:
        return ROCKSDB_NAMESPACE::Tickers::NON_LAST_LEVEL_READ_COUNT;
      case -0x3B:
        return ROCKSDB_NAMESPACE::Tickers::LAST_LEVEL_SEEK_FILTERED;
      case -0x3C:
        return ROCKSDB_NAMESPACE::Tickers::LAST_LEVEL_SEEK_FILTER_MATCH;
      case -0x3D:
        return ROCKSDB_NAMESPACE::Tickers::LAST_LEVEL_SEEK_DATA;
      case -0x3E:
        return ROCKSDB_NAMESPACE::Tickers::
            LAST_LEVEL_SEEK_DATA_USEFUL_NO_FILTER;
      case -0x3F:
        return ROCKSDB_NAMESPACE::Tickers::
            LAST_LEVEL_SEEK_DATA_USEFUL_FILTER_MATCH;
      case -0x40:
        return ROCKSDB_NAMESPACE::Tickers::NON_LAST_LEVEL_SEEK_FILTERED;
      case -0x41:
        return ROCKSDB_NAMESPACE::Tickers::NON_LAST_LEVEL_SEEK_FILTER_MATCH;
      case -0x42:
        return ROCKSDB_NAMESPACE::Tickers::NON_LAST_LEVEL_SEEK_DATA;
      case -0x43:
        return ROCKSDB_NAMESPACE::Tickers::
            NON_LAST_LEVEL_SEEK_DATA_USEFUL_NO_FILTER;
      case -0x44:
        return ROCKSDB_NAMESPACE::Tickers::
            NON_LAST_LEVEL_SEEK_DATA_USEFUL_FILTER_MATCH;
      case -0x45:
        return ROCKSDB_NAMESPACE::Tickers::BLOCK_CHECKSUM_COMPUTE_COUNT;
      case -0x46:
        return ROCKSDB_NAMESPACE::Tickers::BLOCK_CHECKSUM_MISMATCH_COUNT;
      case -0x47:
        return ROCKSDB_NAMESPACE::Tickers::MULTIGET_COROUTINE_COUNT;
      case -0x48:
        return ROCKSDB_NAMESPACE::Tickers::READ_ASYNC_MICROS;
      case -0x49:
        return ROCKSDB_NAMESPACE::Tickers::ASYNC_READ_ERROR_COUNT;
      case -0x4A:
        return ROCKSDB_NAMESPACE::Tickers::TABLE_OPEN_PREFETCH_TAIL_MISS;
      case -0x4B:
        return ROCKSDB_NAMESPACE::Tickers::TABLE_OPEN_PREFETCH_TAIL_HIT;
      case -0x4C:
        return ROCKSDB_NAMESPACE::Tickers::TIMESTAMP_FILTER_TABLE_CHECKED;
      case -0x4D:
        return ROCKSDB_NAMESPACE::Tickers::TIMESTAMP_FILTER_TABLE_FILTERED;
      case -0x4E:
        return ROCKSDB_NAMESPACE::Tickers::READAHEAD_TRIMMED;
      case -0x4F:
        return ROCKSDB_NAMESPACE::Tickers::FIFO_MAX_SIZE_COMPACTIONS;
      case -0x50:
        return ROCKSDB_NAMESPACE::Tickers::FIFO_TTL_COMPACTIONS;
      case -0x51:
        return ROCKSDB_NAMESPACE::Tickers::PREFETCH_BYTES;
      case -0x52:
        return ROCKSDB_NAMESPACE::Tickers::PREFETCH_BYTES_USEFUL;
      case -0x53:
        return ROCKSDB_NAMESPACE::Tickers::PREFETCH_HITS;
      case -0x55:
        return ROCKSDB_NAMESPACE::Tickers::SST_FOOTER_CORRUPTION_COUNT;
      case -0x56:
        return ROCKSDB_NAMESPACE::Tickers::FILE_READ_CORRUPTION_RETRY_COUNT;
      case -0x57:
        return ROCKSDB_NAMESPACE::Tickers::
            FILE_READ_CORRUPTION_RETRY_SUCCESS_COUNT;
      case -0x54:
        // -0x54 is the max value at this time. Since these values are exposed
        // directly to Java clients, we'll keep the value the same till the next
        // major release.
        //
        // TODO: This particular case seems confusing and unnecessary to pin the
        // value since it's meant to be the number of tickers, not an actual
        // ticker value. But we aren't yet in a position to fix it since the
        // number of tickers doesn't fit in the Java representation (jbyte).
        return ROCKSDB_NAMESPACE::Tickers::TICKER_ENUM_MAX;

      default:
        // undefined/default
        return ROCKSDB_NAMESPACE::Tickers::BLOCK_CACHE_MISS;
    }
  }
};
}  // namespace ROCKSDB_NAMESPACE
